### ISSUE TITLE
UIShiny runtime add component not working

### ISSUE THREAD

**Issue by fromkms** [mob-sakai/UIEffect#102]
Hello there!
Started using your awesome UIEffect package and bumped on weird behaviour of shader work in runtime. In editor all works fine, but in runtime build there is just nothing. I'm talking about UIShiny shader - when adding them on the fly to the object.
I have test project that demonstrate this issue, could you take a look please?
Test project in two ways - first run in editor and see that all works fine, then compile for windows build and try the same thing.

Thanks for your work,
Sergey.
[UIEffect-master.zip](https://github.com/mob-sakai/UIEffect/files/2225816/UIEffect-master.zip)

**Comment by fromkms** [comment]
Thanks for reply, @mob-sakai 

Sad to hear that, but it's another reason to review my project architecture. 

Have a good day and keep to delight us with new features,
Sergey.

**Comment by mob-sakai** [comment]
There is a way to add UIShiny at runtime, @fromkms.

1. Move `UI-Effect-Shiny.mat` into Resources directory
1. Modify `UIShiny.OnEnable` as follows

```
protected override void OnEnable()
{
	// vvvv ADDING vvv
	if (!m_EffectMaterial)
		m_EffectMaterial = Resources.Load<Material> ("UI-Effect-Shiny");
	// ^^^^ ADDING ^^^^

	_time = 0;
	base.OnEnable();
}
```

I hope this will help;)

**Comment by mob-sakai** [comment]
![](https://user-images.githubusercontent.com/12690315/43177729-97b7d8fe-9004-11e8-8e45-21bb781f8fda.gif)

**Comment by fromkms** [comment]
Thanks a lot, @mob-sakai 
You're saved my life!

**Comment by mob-sakai** [comment]
In the future, we will support adding component at runtime, based on this way;)
