### ISSUE TITLE
Softmask support?

### ISSUE THREAD

**Issue by digilocker** [mob-sakai/UIEffect#107]
Hi, I've been using your awesome UI-effects in a project, but have been struggling to use them in anything that is softmasked (eg on progress bars within a softmasked scrollrect). There's some documentation on recompiling the shaders to work with it, but haven't had any success so far with enabling the support. Would be awesome to have these effects working within a better mask than what Unity offers.
Any help greatly appreciated!
[Documentation.pdf](https://github.com/mob-sakai/UIEffect/files/2228011/Documentation.pdf)

**Comment by mob-sakai** [comment]
Hi @digilocker 

Sorry, I don't have [SoftMask](https://assetstore.unity.com/packages/tools/gui/soft-mask-80667) asset.
According to [the tutorial document](https://docs.google.com/document/d/1mFEml0JWhR968GG1gVBBTLsJ8ubf_oraW5MBbrvkrb0), you can support soft masks by modifying shaders.

As an example, I modified [UI-Effect-Shiny.shader](https://github.com/mob-sakai/UIEffect/files/2228919/UI-Effect-Shiny.shader.txt).
Does it work properly?

**Comment by mob-sakai** [comment]
Oh, am I mistaken?
Is it a scenario without [SoftMask](https://assetstore.unity.com/packages/tools/gui/soft-mask-80667) asset?

**Comment by digilocker** [comment]
Hi @mob-sakai no its with using the softmask package.  I modified the shiny shader yesterday and got that working fine, (guessing its the same edits you have made too).  The general ui-effect shader I didn't have any success with though, think it was with the frag section of the code and the if endif statements adding the mask anywhere in that block seemed to throw errors for compile.  That's not as big a deal though hopefully for this project the shiny will be enough.  Thanks for your help :)

**Comment by mob-sakai** [comment]
Could you show me your modified UI-Effect.shader and the compile error message?

**Comment by Ashish-Patel** [comment]
How to integrate digilocker in android app. i found one document, but it's not sufficient as api are not getting called.

**Comment by mob-sakai** [comment]
@Ashish-Patel 
I would like to know more information on the issue.
