### ISSUE TITLE
Rebuild takes 13 seconds with UIEffects switching back to Unity window?

### ISSUE THREAD

**Issue by elvisish** [mob-sakai/UIEffect#120]
Since using UIEffects, I get a rebuilding scripts wait for about 13 seconds every time I go back to the Unity window. I'm only using UIShadow, can I delete any of the other scripts or shaders to attempt to alleviate this wait?

**Comment by mob-sakai** [comment]
Hi @elvisish
That's strange ...

Please tell me about your development environment.
* OS (Windows? Mac?)
* Unity Version
* UIEffect version (described in Changelog.md)

**Comment by mob-sakai** [comment]
This is a UIShadow only package.
Please remove `Coffee/UIExtensions/UIEffect` directory before importing.
GUID of UIShadow is not changed.

[UIEffect_UIShadowOnly.unitypackage.zip](https://github.com/mob-sakai/UIEffect/files/2288926/UIEffect_UIShadowOnly.unitypackage.zip)
