### ISSUE TITLE
Soft shadow/outline

### ISSUE THREAD

**Issue by realworld666** [mob-sakai/UIEffect#123]
The readme file says there is a soft shadow option in UIShadow component but I don't see it in the latest release. Am I missing something?

**Comment by realworld666** [comment]
I got the latest from source as those options arent in the latest "release".
I've now got this but I only seem to be getting soft outlines at the corners. The edges still seem hard
![image](https://user-images.githubusercontent.com/284881/44515666-11a63300-a6bb-11e8-80d2-c9e209b4d505.png)

**Comment by mob-sakai** [comment]
Hmm... that’s weird.

The corner seems be blurred, but the edge does not.
Probably because there is no margin (alpha = 0) in the sprite.
Please add margins to the sprite.
