### ISSUE TITLE
The UIEffectCapturedImage is upside down with 'ScreenSpace - Overlay' mode

### ISSUE THREAD

**Issue by SquareLi** [mob-sakai/UIEffect#127]
It's working fine on Android and unity Editor, the issue only exists on ios.

Unity 2018.2.5f1
XCode9
iOS 11.4.1

**Comment by mob-sakai** [comment]
Hi @SquareLi 

Oh, sorry.
I will fix it later, but I cannot test on ios now...

**Comment by mob-sakai** [comment]
Is `Canvas Render Mode` `ScreenSpace - Overlay`?

**Comment by mob-sakai** [comment]
![sep-15-2018 09-01-14](https://user-images.githubusercontent.com/12690315/45579853-10d17d00-b8c6-11e8-8008-1cdee5541c2f.gif)

Reproduced with : 2018.x Editor(Mac)
Not reproduced with : 5.5.x Editor(Mac), 2017.x Editor(Mac)

**Comment by mob-sakai** [comment]
I am confused.
After repeating the test, the issue is no longer reproduced... why?

**Comment by SquareLi** [comment]
Sorry I didn't have time to check this in the past few days. 
Regarding the Canvas, i believe both world space and overylay have the problem. 
I dont see this issue on Editor on Mac. It only happens on ios devices for me.

**Comment by mob-sakai** [comment]
Reproduced with : 5.5.x Editor & Runtime(Windows/DX11)

**Comment by SquareLi** [comment]
Hello! 
The issue in overlay mode is fixed, but the ScreenSpace-Camera mode still has the issue.

**Comment by SquareLi** [comment]
I added a feature that the UIEffectCapturedImage can use any camera instead of just main camera. Not sure if that's the reason, but your fix seems to only work when the canvas of the component is overylay.

**Comment by mob-sakai** [comment]
It did not reproduce in demo scene...
I test in **develop** branch, build with 2018.2.5f1/XCode9.4, run on iPhone6s/iOS 11.4.1.
`Auto Graphics API` is enable.
![image](https://user-images.githubusercontent.com/12690315/45660537-3794eb00-bb34-11e8-9399-e28ebe9aec13.png)

Do you have a reproducible project?

**Comment by SquareLi** [comment]
I will try to make a test project tomorrow. 
It's really odd that it's upside down on some scenes, and totally fine on others. 
Thanks for looking into it!
