### ISSUE TITLE
UICapturedEffectImage does not work with 'ScreenSpace - Overlay' in edit mode

### ISSUE THREAD

**Issue by Scarabay** [mob-sakai/UIEffect#128]
Hello. I can't make it work with this UI mode. On enable canvas (or any child) with UICapturedEffectImage attached to it, an error appears:
[d3d11] attempting to ReadPixels outside of RenderTexture bounds! Reading (0, 0, 290, 452) from (736, 414)

Unity version is 2018.2.2f1

**Comment by mob-sakai** [comment]
Hi @Scarabay 

Thank you for reporting the bug!
I will check it later.

**Comment by mob-sakai** [comment]
Well... on edit mode only?
