### ISSUE TITLE
Question about Blur Effect

### ISSUE THREAD

**Issue by wraithseeker** [mob-sakai/UIEffect#129]
Is there a way for me to blur every image that is a child of a gameobject without adding a UIEffect component to every gameobject that contains an image? 

If I were to add many UIEffects to blur the entire HUD, let's assume 40-80 image components, is the performance cost alot higher than as compared to blurring the entire screen with another different solution?

For example let's say we have a "HUD" gameobject and a "Game Panel Holder" gameobject that are both a child of the UI screen-space canvas.

I want to be able to blur the entire HUD, when I display a panel that is a child of "Game Panel Holder", without adding a UIEffect component to every gameobject that is a child of "HUD" gameobject.

I tried using UIEffectCapturedImage, but I am not sure how do I control which gameobjects is going to be blurred as it blurs the entire screen without being able to exclude gameobjects.

**Comment by wraithseeker** [comment]
I managed to solve this to control which UI gameobjects to blur by capturing an image of the screen first, and then waiting for a frame before showing another UI panel with UIEffectCapturedImage.

**Comment by mob-sakai** [comment]
Hi @wraithseeker 

Sorry for the inconvenience of using UIEffectCapturedImage.
That's right. **It is necessary to wait a frame!**
