### ISSUE TITLE
UIEffectCapturedImage: Black screen with Unity 2018.1+ editor on Windows 

### ISSUE THREAD

**Issue by Scarabay** [mob-sakai/UIEffect#131]
Hello. I installed the new version, but UIEffectCapturedImage now doesn't work at all in any screen space (tested with overlay and camera), just a black screen even in demo scene. Unity version is the same - 2018.2.2f1

**Comment by mob-sakai** [comment]
Hi, @Scarabay 

Hmm, I would like to know more information.
Is OS Windows?
Can you show me a reproducible small project?

**Comment by mob-sakai** [comment]
Ref: #128

**Comment by Scarabay** [comment]
Yes, os is Window 10. Build targer - PC. Here is a project with UIEffect only, same problem.
[https://drive.google.com/open?id=1vi5BMUwUikdSAkhlx105gRqdHHJLxJOd](url)

**Comment by mob-sakai** [comment]
Thanks your help:)
I will test it later!

**Comment by mob-sakai** [comment]
I found the cause of the bug;)
It's **linear color space.**
This issue reproduce with **only editor on Windows.**

### Solution

Change `Editor > Project Settings > Player > (Standalone tab) > Other Settings > Color Space`  to **Gamma.**

![](https://user-images.githubusercontent.com/12690315/46214422-2048cf80-c376-11e8-8eb9-a2f6b5c4cd8c.png)

**Comment by Scarabay** [comment]
Is it possible to make UIEffectCapturedImage work with Linear color space?

**Comment by mob-sakai** [comment]
Maybe, It's OK.

**Comment by Scarabay** [comment]
By the way, in previous version it did work with Linear, but there was another bug I posted here,

**Comment by mob-sakai** [comment]
Reproduce with:
* Unity 2018.1.x, Unity 2018.2.x
* Windows
* Editor
* Play mode
* Linear color space

**Comment by mob-sakai** [comment]
This issue will be fixed in v2.8.3, soon.
