### ISSUE TITLE
Support TextMeshPro

### ISSUE THREAD

**Issue by mob-sakai** [mob-sakai/UIEffect#137]

**Comment by mob-sakai** [comment]
It's... very... difficult...

**Comment by buihuuloc** [comment]
Do you think it's possible?

**Comment by mob-sakai** [comment]
Yes:)
I made a prototype dissolve effect for TextMeshPro.
![](https://user-images.githubusercontent.com/12690315/48592666-c7b4ac80-e98c-11e8-964e-290ce8f00afb.gif)

**Comment by buihuuloc** [comment]
Fantastic works!
Do you think It's possible for Shiny Effect?

**Comment by mob-sakai** [comment]
Yes, but there are some problems with effects for TextMeshPro.
* It is difficult to support all TextMeshPro shaders. There are too many shaders.
* TextMeshPro does not support `IMeshModifier/IMaterialModifier` interfaces.
* You need to enable uv2/uv3 channels of Canvas. Therefore, Unity 5.5 is not supported.

I think that a big refactor will be needed to maintain compatibility with existing features.
First of all, as an experimental feature, I will develop it in another repository...
Please follow me and receive notification of the new repository.

**Comment by buihuuloc** [comment]
Can we have a special repo for supporting Unity 2018.2+?
I think Unity 5.5 is quite old. You should consider updating the minimum Unity version?

**Comment by buihuuloc** [comment]
I would rather choose for supporting from Unity 2018.
Is there any reason for keeping support Unity 5.5?

**Comment by mob-sakai** [comment]
UIEffect supports Unity 5.5 because the APIs related to UIEffect not have been updated.
For now, it seems to work well on Unity 5.5+, Unity 2017.x, Unity 2018.x, Unity 2019.x. (Please tell me if there are bugs!)

However, As you say, Unity 5.5 is quite old and few users are using it.
And now, TMPro has been made free and standardized, so I think that updating the minimum unity version is necessary.

Currently, the APIs I need are as follows:
* Canvas.additionalShaderChannels (5.6+)

**Comment by mob-sakai** [comment]
I am developing a mesh effect for TMPro.
It will also support UIShiny :)
https://github.com/mob-sakai/MeshEffectForTextMeshPro

**Comment by buihuuloc** [comment]
It's awesome.

**Comment by mob-sakai** [comment]
[WIP]
I will release it experimentally.
![](https://user-images.githubusercontent.com/12690315/49716968-bcf1ec80-fc98-11e8-969d-b3920af64dee.gif)

**Comment by buihuuloc** [comment]
Can wait to see it in live!!!!

**Comment by mob-sakai** [comment]
Experimental release:
https://github.com/mob-sakai/ShinyEffectForTMPro

**Comment by mob-sakai** [comment]
In progress. (60%)
I'm sorry to delay release.
I do not have enough hours in my day...

Wish there were more hours in a day!

**Comment by mob-sakai** [comment]
In progress. (90%)
![](https://user-images.githubusercontent.com/12690315/53533025-8495d800-3b3c-11e9-9e94-320f3ec7ad74.png)

Technical problems were almost solved!
I will release it soon.
I must update a usage document...
