### ISSUE TITLE
Detail Blur mode doesn't working on 2018.3+

### ISSUE THREAD

**Issue by Michsky** [mob-sakai/UIEffect#138]
Capture Effect - Detail or Medium blur mode doesn't working on 2018.3 or higher versions. Fast blur is working properly though.

**Comment by mob-sakai** [comment]
Hi @Michsky 

Thanks for your reporting.
Please tell me about your environment.

 - Platform: [e.g. Editor(Windows/Mac), Standalone(Windows/Mac), iOS, Android, WebGL]
 - Unity: [e.g. 2018.3.0b8]
 - UIEffect: [e.g. v3.0.0]

**Comment by Michsky** [comment]
Oh, sorry about that! I tried it on both Windows (10 - x64) and Android (9), probably it's same on the others as well.

**Comment by mob-sakai** [comment]
Many thanks!

**Comment by mob-sakai** [comment]
I tested this issue with demo scene, but it did not reproduce...

![](https://user-images.githubusercontent.com/12690315/48102008-68f48200-e26c-11e8-8f34-32758ae8ed85.gif)

Can you submit a reproducible project for this issue?

### Test Environment

Platform: Editor(Windows/Mac), Standalone(Windows/Mac), Android
Unity version: 2018.3.0b8(Mac/Windows)
Plugin version: v3.0.0

**Comment by Michsky** [comment]
There's no error, however there's a warning that says: "Tiled GPU perf. warning: RenderTexture color surface (1024x2048) was not cleared/discarded. See TiledGPUPerformanceWarning.ColorSurface label in Profiler for info
UnityEngine.Graphics:ExecuteCommandBuffer()"

![2018-11-07_14-05-56](https://user-images.githubusercontent.com/26519448/48128024-49724f00-e296-11e8-8a3d-6eb01ab311b2.gif)

Tested on
Platform: Editor & Build (Windows & Android)
Unity version: 2018.3.0b8
Plugin version: v3.0.0

**Comment by mob-sakai** [comment]
Add `CommandBuffer.ClearRenderTarget` to UIEffectCapturedImage.cs at line 360.
```cs
if (s_CommandBuffer == null)
{
	s_CommandBuffer = new CommandBuffer();
}
s_CommandBuffer.ClearRenderTarget (false, true, Color.clear);	// Add this line!
```
I hope to solve this issue.

**Comment by Michsky** [comment]
That fixed the issue, many thanks for supporting and developing this amazing package!
