### ISSUE TITLE
Integrate with package manager

### ISSUE THREAD

**Issue by buihuuloc** [mob-sakai/UIEffect#141]
Hi @mob-sakai,

Can you give me an idea to let the package works with Package Manager?

Thanks!

**Comment by mob-sakai** [comment]
Hi @buihuuloc 
It's very important :)

I have an idea, but you will need to change the directory structure ...

**Comment by mob-sakai** [comment]
https://forum.unity.com/threads/git-support-on-package-manager.573673/

**Comment by buihuuloc** [comment]
I'm trying to test with npm package. 
However, it isn't working for me

* https://www.npmjs.com/package/uieffectupm

Added two lines in `manifest.json` file

```html
{  
 "registry": "https://registry.npmjs.org",

  "dependencies": {
       "uieffectupm":"4.0.1"
   }
}
```

**Comment by buihuuloc** [comment]
I just published a new version 4.0.2.
And It's working now.  🤗

**Comment by mob-sakai** [comment]
Awesome!
It works fine for me, on 2018.3.0f2!

**Comment by mob-sakai** [comment]
Hmm, this way seems to have a problem.
Uninstalled packages are not displayed in PackageManager...
![](https://user-images.githubusercontent.com/12690315/50381273-41476500-06c6-11e9-92bb-4d497dca7abc.png)

**Error message**
```
Cannot perform upm operation: Package [com.unity.package-manager.metadata] cannot be found [NotFound]
Error searching packages online.
```

**Comment by buihuuloc** [comment]
I found the problem.
We need to use the scope registries, instead of using the global registry.

```json
{
  "scopedRegistries": [
    {
      "name": "UI Effect",
      "url": "https://registry.npmjs.org",
      "scopes": [
        "uieffectupm"
      ]
    }
  ],
  "dependencies": {
    "uieffectupm":"4.0.2"
 }
}
```

**Comment by mob-sakai** [comment]
Excellent, @buihuuloc !

**Comment by mob-sakai** [comment]
Assets in the Package directory can not be modified.
Like TextMeshPro, we may want to package the resource as *.unitypackage.

**Comment by buihuuloc** [comment]
If there a way to handle post-install package event with Package Manager, I think we can do it. 
Otherwise, we can have an editor menu to import the external resources folder.

**Comment by mob-sakai** [comment]
By using the InitializeOnLoadMethod attribute, it is possible to import packages after compilation.

**Comment by mob-sakai** [comment]
>If there a way to handle post-install package event with Package Manager, I think we can do it.

I think it is necessary to implement `IPackageManagerExtension`.

**Comment by JesseTG** [comment]
What if you try [this new thing](https://github.com/ashblue/oyster-package-generator)?

**Comment by mob-sakai** [comment]
Hi @JesseTG 
Maybe, it will work.
