### ISSUE TITLE
UIEffectCapturedImage.effectColor does not work as expected

### ISSUE THREAD

**Issue by HHHHHHHHHHHHHHHHHHHHHCS** [mob-sakai/UIEffect#148]
UIEffectCapturedImage  use serializedObject.FindProperty("m_Color"),but should use serializedObject.FindProperty("m_EffectColor"), so color mode is error.

and if you multiple clicks captures button. Maybe show an error :
Setting mipmap mode of already created render texture is not supported!UnityEngine.RenderTexture:set_useMipMap()Coffee.UIExtensions.UIEffectCapturedImage:Capture() (at Assets/Coffee/UIExtensions/UIEffect/Scripts/UIEffectCapturedImage.cs:346)UnityEditor.EditorApplication:Internal_CallDelayFunctions()

I modified the code to solve this problem.
		void _Release(ref RenderTexture obj)
		{
			if (obj)
			{
			        obj.Release();//my Add
				RenderTexture.ReleaseTemporary (obj);
				obj = null;
			}
		}

**Comment by mob-sakai** [comment]
Hi @HHHHHHHHHHHHHHHHHHHHHCS 
Thank you for reporting.
Clearly, they are bugs!
