### ISSUE TITLE
Improve performance: UIEffect

### ISSUE THREAD

**Issue by mob-sakai** [mob-sakai/UIEffect#150]

**Comment by buihuuloc** [comment]
Hi @mob-sakai 
Is there any update for that?

**Comment by mob-sakai** [comment]
Hi @buihuuloc 
I am sorry for the late update.
Several attempts have been successful.
* Vertex does not increase when using Advanced Blur
* Shader Refactoring

However, work is delayed due to some bugs in UIEffectCapturedImage.
I might split UIEffectCapturedImage into another project.

**Comment by buihuuloc** [comment]
Thanks @mob-sakai
