### ISSUE TITLE
Add support for Texture Atlas / Sprite Diced Images

### ISSUE THREAD

**Issue by wraithseeker** [mob-sakai/UIEffect#151]
It would be nice if UIEffect supports sprites made from sprite texture through [sprite dicing](https://github.com/Elringus/SpriteDicing) as well.

**Comment by mob-sakai** [comment]
I will make a new SpriteDicedPacker for this issue.
Please wait for the release, and [follow me](https://github.com/mob-sakai)! :)

**Comment by wraithseeker** [comment]
Awesome 👍
