### ISSUE TITLE
这个项目实在是太棒了  好喜欢！

### ISSUE THREAD

**Issue by JiuMengDz** [mob-sakai/UIEffect#152]

**Comment by mob-sakai** [comment]
谢谢！
还请看看我的其他项目！

**Comment by mob-sakai** [comment]
我打算立即发布v3.1.0。:)
它支持TextMeshPro。
![](https://user-images.githubusercontent.com/12690315/53564447-4929f680-3b9a-11e9-9eed-2599cd033846.png)
