### ISSUE TITLE
Amazing works bro :)

### ISSUE THREAD

**Issue by DaivyIsHere** [mob-sakai/UIEffect#155]
Thanks a lot for making these amazing assets !!!
I'm really looking forward to use these effects on sprites soon :))

**Comment by mob-sakai** [comment]
Hi @DaivyIsHere 
Thank you for using my assets. :)

Please know that English is not my native language, and I may make some confusing mistakes.
You want to apply effect to SpriteRenderer, don't you?

**Comment by DaivyIsHere** [comment]
Dont worry English is not my first language either.

And yes, is it possible to apply effects to spriteRenderer?

**Comment by mob-sakai** [comment]
Yes, I think it is possible. :)
However, shaders and components need to be modifiered.
First of all, I will develop it in another repository.
And it **may be integrated** into UIEffect.

...Is it no longer "UI" Effect? :trollface:

**Comment by DaivyIsHere** [comment]
Nice :)) Can't wait to use your new assets :D
You can name it 2D & UI Effects 🎉

**Comment by mob-sakai** [comment]
ref #157
