### ISSUE TITLE
3.1.0 [Android][2018.3.2 LWRP]Image Capture Pitching black no blurr

### ISSUE THREAD

**Issue by AbrahamArmasCordero** [mob-sakai/UIEffect#162]
**Describe the bug**
3.1.0 [Android][2018.3.2 LWRP]Image Capture Pitching black  and not doing the blur when activate, very similar to the Issue "UICapturedEffectImage does not work with LWRP" 

**To Reproduce**
put the image capture in a gameobject in scene tell it to be what ever (dont check the immediate capture box)
Then tell another button to activate anyway via Capture() or with the capture OnEnable()
(I'll post a small reproduction project tomorrow)
Then it will turn the screenshoot black and if u have alpha it will apply the alpha to it

**Environment (please complete the following information):**
Editor Working fine
Android Build not working (mobile tested Motorola G5)

**Additional context**
It worked before in some version of UIEffect, im trying to see in what version it worked but im not finding the broken commit, when i find it ill post it. (havent change the scene)

**LWRP Settings**
![image](https://user-images.githubusercontent.com/36243865/54873473-499f6100-4dd7-11e9-88de-52f9444b6ad5.png)

**Graphic settings**
![image](https://user-images.githubusercontent.com/36243865/54873494-92571a00-4dd7-11e9-836b-d3928bd42a3e.png)

**Comment by mob-sakai** [comment]
Hi @AbrahamArmasCordero 
Thank you for reporting!
I am waiting for your submission. :)

**Comment by AbrahamArmasCordero** [comment]
i got a commit where it is working exac same scene settings i cant see version of UI Effect changelong is like this" ./../../../../CHANGELOG.md" also License and readme are like that, im doing binary search throw my commits to see failure point

**Comment by mob-sakai** [comment]
Ah...
You installed UIEffect **without** .unitypackage, right?
Show me UICapturedImage.cs in your project.
I can find the version with it. :)

**Comment by AbrahamArmasCordero** [comment]
i Have gone to the commit that this brakes then went back right to the commit that this works, and tried to brake with the same changes,  it didnt brake :/ there is only change in:
- the LWRP options 
- Quality Settings
- Scene GameObject and of those object there are only changes in Camera, Lights, and Image Capture Script

**Comment by AbrahamArmasCordero** [comment]
Solved. i changed the Graphics API Order Of preference I guess ****  idk why i change things of render languages idk them yet i just thought i didn't matter but it does *sigh*

**Solved**
![image](https://user-images.githubusercontent.com/36243865/54880670-7a1ee380-4e47-11e9-90ec-4375b0cb5024.png)

**Before Solved** 
![image](https://user-images.githubusercontent.com/36243865/54880677-8d31b380-4e47-11e9-80db-eb09e1930705.png)

Im sorry i made you waste time reading

**Comment by mob-sakai** [comment]
Thanks!
I'll check it later! :)
