### ISSUE TITLE
Bug when i build and run file APK

### ISSUE THREAD

**Issue by helloo0-0oword** [mob-sakai/UIEffect#164]
![Screen Shot 2019-04-16 at 14 20 22](https://user-images.githubusercontent.com/32776884/56189774-fa092980-6052-11e9-9fb8-53c31ba8f268.png)

My version unity: 2018.2.14f1 Personal (64 bit) and i use macbook

**Comment by helloo0-0oword** [comment]
Can you help me pls 👍

**Comment by mob-sakai** [comment]
Hi @helloo0-0oword 
Do you add an UIEffect component at runtime?

**Comment by mob-sakai** [comment]
I would like to know more information on this issue.

- UIEffect version
- behavior on iOS

**Comment by helloo0-0oword** [comment]
I don't understand when I used the demo version to export the APK file, it still reported an error.

My UIEffect version: 

# Changelog

## [v3.1.0](https://github.com/mob-sakai/UIEffect/tree/v3.1.0) (2019-03-10)

[Full Changelog](https://github.com/mob-sakai/UIEffect/compare/v3.0.4...v3.1.0)

## Support TextMeshPro!

* All components are supported
* Advanced blur is supported for Unity 2017.1+

![](https://user-images.githubusercontent.com/12690315/53533025-8495d800-3b3c-11e9-9e94-320f3ec7ad74.png)

For details to use, see [Usage with TextMeshPro](https://github.com/mob-sakai/UIEffect#usage-with-textmeshpro)

**NOTE: Unity 5.x will not be supported in the near future**

**Implemented enhancements:**


![Screen Shot 2019-04-16 at 22 30 57](https://user-images.githubusercontent.com/32776884/56223134-6279fa00-6097-11e9-8f03-4199475480a5.png)

**Comment by mob-sakai** [comment]
Can you submit a reproducible project (*.zip) for this issue?

**Comment by helloo0-0oword** [comment]
You can see the error right on UIEffect_demo. See my pic 

![Screen Shot 2019-04-16 at 23 01 07](https://user-images.githubusercontent.com/32776884/56225526-c30b3600-609b-11e9-8740-cbae42afc80c.png)

**Comment by mob-sakai** [comment]
hmm
1. Did you install TextMeshPro?
2. Did you Remapped GUID for TextMeshPro?
https://forum.unity.com/threads/migrating-from-legacy-asset-store-to-package-manager-releases.511748/

**Comment by mob-sakai** [comment]
The TextMeshPro objects in demo scene is legacy (asset store) version.
Therefore, remapping is necessary.

**Comment by mob-sakai** [comment]
In the near future, UIEffect will stop supporting legacy versions of TextMeshPro.

**Comment by helloo0-0oword** [comment]
i don't understand but it not work for me :(
![Screen Shot 2019-04-16 at 23 25 21](https://user-images.githubusercontent.com/32776884/56227152-ff8c6100-609e-11e9-84e7-acfdba4bab89.png)

**Comment by mob-sakai** [comment]
OK,
Let's forget about the demo scene.
Please try the following:

1. Add a TextMeshProUGUI object to the scene.
1. Set the font and text as you like.
2. Add a UIShiny component.
1. If a warning appears in the inspector, click `Fix` button.

**Comment by helloo0-0oword** [comment]
is it right ?
![Screen Shot 2019-04-17 at 00 12 21](https://user-images.githubusercontent.com/32776884/56230027-86dcd300-60a5-11e9-99b3-ad3da73fbde5.png)

**Comment by helloo0-0oword** [comment]
I don't see warning appears in the inspector.

![Screen Shot 2019-04-17 at 00 22 39](https://user-images.githubusercontent.com/32776884/56230666-f901e780-60a6-11e9-88bd-324d34a59017.png)
![Screen Shot 2019-04-17 at 00 22 51](https://user-images.githubusercontent.com/32776884/56230667-f99a7e00-60a6-11e9-9a3e-6cdbd6b52ba0.png)

**Comment by helloo0-0oword** [comment]
yeah Thank you, I fixed the error

**Comment by mob-sakai** [comment]
Add a symbol TMP_PRESENT to scripting define symbols.
See https://github.com/mob-sakai/UIEffect#usage-with-textmeshpro for details.
