### ISSUE TITLE
UIShiny effect remain on screen after calling Stop()

### ISSUE THREAD

**Issue by DenL** [mob-sakai/UIEffect#165]
**Describe the bug**
Of the UIShiny effect, if .Stop() is called during the middle of a shiny effect, the image will still have the static shiny effect.

**To Reproduce**
1. Place a UI shiny script on a gameobject with Image
2. Enter play mode, trigger the shiny effect
3. Stop() the shiny effect when the "shine" is still visible
4. The "shine" effect will stop moving and remains on screen

**Environment (please complete the following information):**
 - Platform: Editor
 - Unity: 2019.1.0f2
 - UIEffect: 3.1.0

**Comment by DenL** [comment]
Not sure if this is the intended behavior, but I have been enabling/disabling the uishiny script instead of Play() Stop() to get around this.

**Comment by mob-sakai** [comment]
Hi @DenL 
Thank you for reporting!

**Comment by mob-sakai** [comment]
I think we need the following method:
* `Play (bool reset = true)`
* `Stop (bool reset = true)`
