### ISSUE TITLE
Setting the sprite cause image to disappear

### ISSUE THREAD

**Issue by MoDDiB** [mob-sakai/UIEffect#173]
**Describe the bug**
if you change the sprite with the code and the image as a UIEffect the Image will disappear.

**To Reproduce**
1. Create an image
2. Add a monobehavior to set another sprite during the update
3 Set a UIEffect
4. The image will disappear

**Environment (please complete the following information):**
 - Platform: Editor Windows
 - Unity: 2019.1.4.f1
 - UIEffect:3.1.0

**Comment by mob-sakai** [comment]
Hi @MoDDiB 
Thank you for your reporting!

**Comment by mob-sakai** [comment]
Did you add a UIEffect component while in play mode?
If so, it is not supported.

**Comment by M0rph3v5** [comment]
Also there's a known unity bug at the moment where if you set the sprite on uiimage components at runtime they dissappear. If you set the overridesprite it still works.

**Comment by mayura33** [comment]
Any resolution for above issue? i am also facing the same problem.!

**Comment by mob-sakai** [comment]
it seems there is a bug...

**Comment by mayura33** [comment]
Can we expect any release date for above bug fix? if then please let us know :)

**Comment by mob-sakai** [comment]
@mayura33 

I cannot give you an ETA at this time. Sorry.
