### ISSUE TITLE
UIEffectCapturedImage: on android have no effect 

### ISSUE THREAD

**Issue by xiangyuan** [mob-sakai/UIEffect#174]
mac editor is ok 
but on android the blur effect can not be feel

**Environment (please complete the following information):**
 - Platform: [e.g. Editor Mac is Ok
 - Unity: [e.g. 2019.1.8f]
 - UIEffect: [e.g. branch master]

**Additional context**
Add any other context, screenshots or gif animations about the question here.

*****all resource is build assetbundle*****

1. here is on the mac editor and the component parameters, all is ok.

![image](https://user-images.githubusercontent.com/914843/60263296-deec4d00-9912-11e9-93b8-93a661211fb4.png)

2. now seam parameter on android device, the blur effect just like don't have.
![image](https://user-images.githubusercontent.com/914843/60263469-55894a80-9913-11e9-89fe-be953c6d8864.png)

3. one more thing , if the immediate capturing not toggle the android device blur is black
![image](https://user-images.githubusercontent.com/914843/60263556-84072580-9913-11e9-88da-a20fd70b35a2.png)

**Comment by mob-sakai** [comment]
Hi @xiangyuan 
Thank you for your reporting!

Can you test under different conditions?
* Graphics api priority: Turn off Auto Graphics API for Android and reordering the list in player settings
  * OpenGL ES 2.0
  * OpenGL ES 3.0
  * Vulkan

**Comment by NilokiloxD** [comment]
I had the same issue, only forcing to open gl 2.0 solved it. Open gl 3.0 and Vulkan and maybe even metal are not working.

Any plans for supporting them?

**Comment by mob-sakai** [comment]
Hi @xiangyuan 
Thank you for your reporting.

I hope solve it.
However, to be honest, I do not know how to solve it. :(
Probably, I should use GPU debugger.

**Comment by xiangyuan** [comment]
@mob-sakai  i have make a test,  click a button the invoke the capture method. invoke many times(5 ~6)
then the  blur effect can say,  the graphics order as follow.
![image](https://user-images.githubusercontent.com/914843/60636820-9a990980-9e4a-11e9-9749-9bbf8a834495.png)

maybe some blur algorithm problem.  thanks your great project.

**Comment by mob-sakai** [comment]
Thank you, @xiangyuan

**Comment by xiangyuan** [comment]
@mob-sakai  i know the problem.  if i use assetbundle to compile package apk, which will hove no effect. but if i move the shaders and mat to resources to package apk. it will work.

not about graphics order list.   thanks again.

**Comment by mob-sakai** [comment]
@xiangyuan 
Oh...
Hmm, I should change architecture of this plugin again...

**Comment by mob-sakai** [comment]
Thank you for your information!
