### ISSUE TITLE
Different Material per Effect

### ISSUE THREAD

**Issue by jakeslack27** [mob-sakai/UIEffect#175]
Hi,

I'm trying to use the effect to have a dissolve effect on my UI.Image component.  This is working well except I would like to have two versions of the Image - one with ZTest set to false and another set to true (so when the object is occluded, you can see a faint version of the Image).  However, when I try to use a different material/shader for the UIEffect it resets to the default.  Is there a way around this?

Thanks, Jake

**Comment by mob-sakai** [comment]
Hi @jakeslack27 
Thank you for using this plugin!

You want to use custom material and shader with UIEffect component, right?

**Comment by jakeslack27** [comment]
Thank you for the fast response!  That is right, I'd like to use a custom shader that has ZTest set to true so I can do overlay variety

**Comment by mob-sakai** [comment]
Oh, I see.
Wait a minute!

**Comment by mob-sakai** [comment]
At the moment, UIEffect does not support it.
In order to use a custom material, try following steps.

1. Modify `UIDissolve.cs` to prevent the change of effectMaterial.
```
protected override Material GetMaterial()
{
    if (isTMPro)
    {
        return null;
    }
    return m_EffectMaterial; // ADD THIS LINE
    // return MaterialResolver.GetOrGenerateMaterialVariant(Shader.Find(shaderName), m_ColorMode); // REMOVE THIS LINE
}
```
2. Set custom material to `Effect Material` in inspector view (Debug mode.)
![image](https://user-images.githubusercontent.com/12690315/60398159-3f3bf280-9b90-11e9-9964-39727fff5e90.png)
3. If you need, set material keyword `ADD` in inspector view (Debug mode) to use additional color mode.
![](https://user-images.githubusercontent.com/12690315/60398219-d7d27280-9b90-11e9-9bb6-aa611797d73a.png)

**Comment by mob-sakai** [comment]
I will implement this feature in the near future. :)

**Comment by jakeslack27** [comment]
Hi,

I have tried following your instructions but unfortunately it doesn't seem to work for me.  The initial change of the material works but as soon as I save the scene/apply prefab/play the scene my UI.Image component resets to the default material.  Any additional step that could prevent that from happening?

Thanks, Jake

**Comment by mob-sakai** [comment]
Hi @jakeslack27 
Ok, I will test it later.

**Comment by jakeslack27** [comment]
ありがといございます！

**Comment by jakeslack27** [comment]
Hi Takashi san, any update on this!?

Thanks!

*Jake Slack*
Software Developer


+44 203 865 3327 <020%203865%203327>
ali@synertial.comwww.synertial.com
<http://www.synertial.com/>www.mocapsuit.com
<http://www.synertial.com/>UK: 57, Grange Road, Lewes, East Sussex,
BN7 1TU, UK
Taiwan: 4F, 266, SongJiang Rd. Taipei 10437, Taiwan, R.O.C
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

The information transmitted is intended only for the person or entity
to which it is addressed and may contain confidential and/or
privileged material. Any review, re-transmission, dissemination or
other use of, or taking of any action in reliance upon, this
information by persons or entities other than the intended recipient
is prohibited. If you received this in error, please contact the
sender and delete the material from any computer.

**Comment by mob-sakai** [comment]
Hi @jakeslack27
Sorry for my late reply.

That's strange. It seems like its working for me...
Hmm, maybe you have set your material to Image.Material?
Set your material to UIDissolve.EffectMaterial.

**Comment by jakeslack27** [comment]
Sorry I'm a little confused.  

When I set the material in UIDissove.EffectMaterial & the material in Image.Material to the correct material like so:

![image](https://user-images.githubusercontent.com/20554653/60938448-fa8e2500-a30e-11e9-95ae-987e512be01c.png)

As soon as I hit Play or apply the prefab it resets to a hidden material I don't want to use:

![image](https://user-images.githubusercontent.com/20554653/60938486-1a254d80-a30f-11e9-9883-9240e6eb191a.png)

What am I missing?

**Comment by jakeslack27** [comment]
Perhaps there is an easier way to achieve what I want to do?  I simply want a small change in some of my UIDissolves to have their ZTest set to Always.

**Comment by mob-sakai** [comment]
OK @jakeslack27 
There is a simple solution (with small changes) for that.
It use shader keyword.

Just a moment please.

**Comment by mob-sakai** [comment]
最も簡単な解決方法：
UIDissolve.cs L49
```
[Tooltip("Compare function.")]
[SerializeField] UnityEngine.Rendering.CompareFunction m_CompareFunction;
```
```

**Comment by mob-sakai** [comment]
Add code as following:

* UIDissolve.cs L49
```
[Tooltip("Compare function.")]
[SerializeField] UnityEngine.Rendering.CompareFunction m_CompareFunction;
```
* UIDissolve.cs L255
```
hash += ((ulong)m_CompareFunction << 38);
```
* UIDissolve.cs L281
```
mat.SetInt("unity_GUIZTestMode", (int)m_CompareFunction);
```
* UIDissolveEditor.cs L112
```
EditorGUILayout.PropertyField(serializedObject.FindProperty("m_CompareFunction"));
```
**NOTE:** This solution does **not** require an extra shader.

[source.zip](https://github.com/mob-sakai/UIEffect/files/3378638/source.zip)

**Comment by jakeslack27** [comment]
Awesome :)

Thank you so much for your help - I've managed to get the overlay working.  However, there are two minor issues still remaing before I have the super, beautiful level of polish I'm looking for.

1. The Compare Function doesn't seem to work on TextMeshPros so the overlay doesn't happen.
2. The Color from the UI.Image doesn't seem to be filtering into the final material.  I would like to show the overlay material at about 1/4 the opacity of the original but even with the alpha down it still shows full alpha.

![OcclusionNone](https://user-images.githubusercontent.com/20554653/61050322-bd668780-a421-11e9-8d6b-00e74c4176ba.png)
No occlusion

![Occlusion](https://user-images.githubusercontent.com/20554653/61050334-c35c6880-a421-11e9-8160-94a473009a74.png)
With occlusion

**Comment by mob-sakai** [comment]
Oh, that's a beautiful scene. :)
Just a moment please.

**Comment by mob-sakai** [comment]
Hmm, CanvasGroup.alpha does not affect UIEffect.
It is a bug.

**Comment by jakeslack27** [comment]
ありがとうございます :)

Let me know if I can do anything to help?  私を手伝てくれてありがとう！

*Jake Slack*
Software Developer


+44 203 865 3327 <020%203865%203327>
ali@synertial.comwww.synertial.com
<http://www.synertial.com/>www.mocapsuit.com
<http://www.synertial.com/>UK: 57, Grange Road, Lewes, East Sussex,
BN7 1TU, UK
Taiwan: 4F, 266, SongJiang Rd. Taipei 10437, Taiwan, R.O.C
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

The information transmitted is intended only for the person or entity
to which it is addressed and may contain confidential and/or
privileged material. Any review, re-transmission, dissemination or
other use of, or taking of any action in reliance upon, this
information by persons or entities other than the intended recipient
is prohibited. If you received this in error, please contact the
sender and delete the material from any computer.

**Comment by mob-sakai** [comment]
@jakeslack27 
It seems to be working fine. :)
(Z test always and transparent)
![Jul-12-2019 23-44-57](https://user-images.githubusercontent.com/12690315/61136752-1bb56800-a4ff-11e9-9d68-02ac5bc0858b.gif)

1. Import the following unitypackage
[fix.unitypackage.zip](https://github.com/mob-sakai/UIEffect/files/3386852/fix.unitypackage.zip)
2. Select the dissolve material for TextMeshPro in project view
3. Set compare function to "Always" in material inspector view
![](https://user-images.githubusercontent.com/12690315/61137682-f45f9a80-a500-11e9-90d5-d7db4af3ddab.png)



If you need a material using another CompareFunction, duplicate the dissolve material and use it.

**Comment by jakeslack27** [comment]
![6d3054ded19d3d0dc08d1e6ccfa62f7a](https://user-images.githubusercontent.com/20554653/61346610-6be05180-a894-11e9-9bd1-6fbe697fb1a6.gif)

できた、よかった。ほんとにありがとうございます！

**Comment by mob-sakai** [comment]
I’m happy to hear that :smile::+1:

**Comment by mob-sakai** [comment]
This feature will be integrated in UIEffect v4.x :+1:
