### ISSUE TITLE
UICaptured EffectImage: ignore blur for ui elements

### ISSUE THREAD

**Issue by antim0118** [mob-sakai/UIEffect#177]
**Describe the question**
_UICaptured EffectImage_ captures UI elements. How to exclude blur from UI elements?

**Environment:**
 - Platform: Editor(Windows), Android,
 - Unity: 2019.1.8f1
 - UIEffect: v3.1.0

**Comment by mob-sakai** [comment]
Hi @antimYT 
UICapturedEffectImage captures the screen of the previous frame.
After capturing, please activate the UI element in front of UICapturedEffectImage.

**Comment by antimYT** [comment]
It is always in front of UI element.

Thats what i mean
![uiproblem](https://user-images.githubusercontent.com/22983870/60756961-b86a9800-a01d-11e9-9af8-afc52fc2a12f.gif)

**Comment by mob-sakai** [comment]
Hmm...?
I would like to know more information.
Can you attach a minimal repro project for this question?
