### ISSUE TITLE
TMP Pro error

### ISSUE THREAD

**Issue by buihuuloc** [mob-sakai/UIEffect#179]
Hi @mob-sakai 
Did you get this issue

```
Mesh.vertices is too small. The supplied vertex array has less vertices than are referenced by the triangles array.
UnityEngine.Mesh:set_vertices(Vector3[])
TMPro.TextMeshProUGUI:GenerateTextMesh() (at Library/PackageCache/com.unity.textmeshpro@2.0.1/Scripts/Runtime/TMPro_UGUI_Private.cs:4070)
TMPro.TextMeshProUGUI:OnPreRenderCanvas() (at Library/PackageCache/com.unity.textmeshpro@2.0.1/Scripts/Runtime/TMPro_UGUI_Private.cs:1656)
TMPro.TextMeshProUGUI:Rebuild(CanvasUpdate) (at Library/PackageCache/com.unity.textmeshpro@2.0.1/Scripts/Runtime/TextMeshProUGUI.cs:209)
UnityEngine.Canvas:SendWillRenderCanvases()
```

**Comment by mob-sakai** [comment]
Hi @buihuuloc 
Hmm, I know a similar issue.
https://github.com/mob-sakai/MeshEffectForTextMeshPro/issues/6

Did you use `UIShadow` component or `UIEffect` component with `AdvancedBlur` ?

**Comment by buihuuloc** [comment]
I used UIShadow and UIEffect without AdvanceBlur

**Comment by mob-sakai** [comment]
To be honest, in some cases, UIShadow and AdvancedBlur do not work well with TMPro.

**Comment by mob-sakai** [comment]
Can you use TMpro's features instead?
* Underlay
* Outline

**Comment by buihuuloc** [comment]
TMPP Outline is not good as your.
I hope you can somehow fix in soon

**Comment by johnrossporter** [comment]
I am having this issue as well. It seems to happen a lot when the TextMeshPro with UIShadow is a child of a gameobject with ContentSizeFitter and a LayoutGroup.

TMP shadow/outline effect doesn't seem to work with bitmap fonts, no that's not an option.

**Comment by mob-sakai** [comment]
Sorry for my late reply.

UIEffect v5 is now released.
Please try it. :+1:
[🔄 Upgrading from v4 to v5](https://github.com/mob-sakai/UIEffect?tab=readme-ov-file#-upgrading-from-v4-to-v5)
