### ISSUE TITLE
New architecture: Shader-first design

### ISSUE THREAD

**Issue by mob-sakai** [mob-sakai/UIEffect#181]
* [ ] IMPORTNANT CHANGES
  * [ ] UIEffect will no longer support Unity 2018.1 or earlier
    * [ ] To use `IPreprocessShaders` API
    * [ ] TextMeshPro is provided by package manager
  * [ ] In the future, UIEffect will only support Unity2018.3 or later
    * [ ] To integrate with package manager
* [x] Effect materials will be generated on demand
  * [x] Material repository generates a material from shader and variant parameters
  * [x] Effect component refers shader variant parameters, not a material
* [ ] Strip shader variants switch config
https://blogs.unity3d.com/2018/05/14/stripping-scriptable-shader-variants/
  * [ ] Remove unnecessary shader variants on preprocess
  * [ ] This API has been added in Unity 2018.2
  * [x] Change `shader_feat` to `multi_compile` in shader
* [x] Runtime adding effect component will be supported
* [x] Easy to use effect for TextMeshPro
  * [x] No pre-generated materials are required

**Comment by buihuuloc** [comment]
OMG, It looks promising. 
Do you have the ETA?

**Comment by mob-sakai** [comment]
Hi @buihuuloc 
No, but alpha (experimental) version will be released later this month. 👍

**Comment by buihuuloc** [comment]
Is there a way to upgrade from v3 to v4?

**Comment by mob-sakai** [comment]
Yes, automatically.

**Comment by buihuuloc** [comment]
Awesome!!!

**Comment by NilokiloxD** [comment]
Will this also include a fix for the blur shader being completly black in gles3 and vulkan for some devices? Would be awesome!

**Comment by mob-sakai** [comment]
@NilokiloxD
I am trying to fix it but it is still broken... X(
In near future, I will separate `UIEffectCapturedImage` into another project to fix.

**Comment by buihuuloc** [comment]
Hey @mob-sakai 
Would you mind to update us about the status?

**Comment by mob-sakai** [comment]
Hi @buihuuloc 
Alpha version is under development in `develop_v4` branch.
First alpha version (4.0.0-alpha1) will be released at the end of this month.

**Comment by mob-sakai** [comment]
Roadmap for v4.0.0  #185

**Comment by buihuuloc** [comment]
Awesome!

**Comment by mob-sakai** [comment]
I'm sorry.  The release of the alpha version is delayed.

**Comment by mob-sakai** [comment]
Sorry for my late reply.

UIEffect v5 is now released.
Please try it. :+1:
[🔄 Upgrading from v4 to v5](https://github.com/mob-sakai/UIEffect?tab=readme-ov-file#-upgrading-from-v4-to-v5)
