### ISSUE TITLE
[WIP] v4.0.0 Release Summary

### ISSUE THREAD

**Issue by mob-sakai** [mob-sakai/UIEffect#185]
**NOTE: v4.0.0 is under development on `develop_v4` branch.**
**Current: 4.0.0-alpha1**

### New architecture: more, more easier to use
* Simpler workflow and out of the box features
* Support adding the effect component at runtime
* The effect for TextMeshPro does not require pre-generated materials
* Use texcoord2 and texcoord3 as default

### Shader stripping
* Remove unnecessary shader variants on preprocess (for Unity 2018.2 or later)

### Support Unity Package Manager (UPM)
* You can install UIEffect using UPM, or install under Packages directory

### UIEffectCapturedImage will be separated from UIEffect
* For faster release
* UIEffectCapturedImage will be refactored as another project and work independently
* You can install it using UPM, or install under Packages directory

### UIEffect will no longer support Unity 2017 or earlier
* For faster release
* It may work but is not recommended

### Documentation
* Usage of all features
* API reference
* Demos

**Comment by mob-sakai** [comment]
## Loadmap for v4.0.0

### v4.0.0-alpha1 (19/07/31)
* Experiment of new architecture
* Support Unity Package Manager (UPM)
* UIEffectCapturedImage will be separated from UIEffect
* Simple demo

### v4.0.0-alpha2 (19/08/x)
* Shader stripping
  * Built asset size test
* Fix bugs

### v4.0.0-alpha3 (19/x/x)
* Demo and test
* Documentation
  * Use docFx
* Fix bugs
* Refactor

### v4.0.0-beta (19/x/x)
* Fix bugs

### v4.0.0 (19/x/x)
* Release

**Comment by buihuuloc** [comment]
Hello there,
Is there any update for the new version?

**Comment by mob-sakai** [comment]
Hi @buihuuloc 

Sorry for development so late.
I am busy and I cannot spend much time on this project... X(

I will release new alpha version in the near future.

**Comment by mob-sakai** [comment]
Sorry for my late reply.

UIEffect v5 is now released.
Please try it. :+1:
[🔄 Upgrading from v4 to v5](https://github.com/mob-sakai/UIEffect?tab=readme-ov-file#-upgrading-from-v4-to-v5)
