### ISSUE TITLE
Is there a way to know when Hide or Show is completed with dissolve?

### ISSUE THREAD

**Issue by ColorTwist** [mob-sakai/UIEffect#188]
Great asset!
As the title suggests, I am looking for a way to know that Hide or show is completed to be able to do some action, is that possible?

Also, a feature request: 
I am trying to make a transaction between menus that contains UI elements (buttons, text, and images).
Like screens dissolving with all of there ui elements.
I want to pass from Menu 1 to Menu 2 by dissolving Menu1 with all of its children.

Using unity 2019.1.11

**Comment by mob-sakai** [comment]
Hi @ColorTwist 
Thank you for your feature request!

**Comment by ColorTwist** [comment]
Great, look forward! :)
A great asset you have there!
