### ISSUE TITLE
ColorMode setter for UI Effect

### ISSUE THREAD

**Issue by SlavomirDurej** [mob-sakai/UIEffect#195]
Hello, first of all, MANY MANY thanks for your excellent work! 

I've got a project that requires a runtime change of Color mode (From Multiply to Add) for the UI Effect component. Unfortunately there's no setter in the UIEffect.cs, I've tried adding :
(on line 182)
		public ColorMode colorMode
		{
			get
			{
				return m_ColorMode;
			}
			set
			{
				m_ColorMode = value;
				GetMaterial();
				UpgradeIfNeeded();
			}
		}

but it did not work properly, it showed Add mode in the UI, but actually it was still multiply mode assigned...

Is there a way to do this ? At least maybe some workaround?

**Comment by mob-sakai** [comment]
Hi @SlavomirDurej 

Thank you for using this plugin. :)

The current version (v3) does not support changing color mode on runtime...
It will be supported in v4. #185
