### ISSUE TITLE
About the codes next to AddComponent<UIEffect>();

### ISSUE THREAD

**Issue by atkdefender** [mob-sakai/UIEffect#198]
void Start()
    {
        UIEffect uiEffect = gameObject.AddComponent<UIEffect>();
        uiEffect.effectMode = EffectMode.Sepia; //Error[0]
        uiEffect.effectFactor = 1f;
        uiEffect.effectColor = Color.white;
        uiEffect.colorMode = ColorMode.Fill; //Error[1]
        uiEffect.colorFactor = 1f;
    }

//Error[0]: Assets\AddUiEffect.cs(12,9): error CS0200: Property or indexer 'UIEffect.effectMode' cannot be assigned to -- it is read only
//Error[1]: Assets\AddUiEffect.cs(15,9): error CS0200: Property or indexer 'UIEffect.colorMode' cannot be assigned to -- it is read only

So the effectMode/colorMode can only be changed in the inspector?

**Comment by mob-sakai** [comment]
Hi @atkdefender 

Yes, they are read only properties.
In next release version (v4.0.0), they will be changed with script. :+1:

**Comment by atkdefender** [comment]
Got it.
Thank you for answering. And an awesome asset! 
I got a UI blur shadow that can use in my game.
