### ISSUE TITLE
the capture screen  image effect  no use in 2019.2+?

### ISSUE THREAD

**Issue by xiangyuan** [mob-sakai/UIEffect#199]
- Platform: [e.g. Editor mac target ios platform
 - Unity: [e.g. 2019.2+]
 - UIEffect: [e.g. v3.2.0]

**Comment by xiangyuan** [comment]
![image](https://user-images.githubusercontent.com/914843/72770378-a8707980-3c38-11ea-8499-a29dd9a6a1e1.png)
i just found  if this line commented  the result can fix.

one more thing . if i packet the capture shader and capture mat in one assetbundle then in ab mode screen image effect will lost (missing effect material),

**Comment by mob-sakai** [comment]
Hi @xiangyuan 
Thank you for your reporting!
