### ISSUE TITLE
Reboot this project

### ISSUE THREAD

**Issue by mob-sakai** [mob-sakai/UIEffect#203]
Hi everyone,

It's been a long time since this project was last updated.
Sorry, I could hardly spend time on this project...

I know you are waiting for UIEffect v4.
The alpha version has not yet been released.
v4 is currently under development, but has some technical issues.

- Fast blur
  - #196
  - Implementation not successful
- Upgrade from v3.x
  - Architecture has changed significantly
  - Difficult to upgrade automatically
- TMPro support
  - Should be supported as a separate package
  - Even if most users have TMPro installed.
- Demo
  - I do not want to use `*.unitypackage` file
  - Demos should be under `Samples~`
  - A menu should be added for 2018.x
- Access to internals/privates
  - Use [OpenSesameCompiler](https://github.com/mob-sakai/OpenSesameCompilerForUnity) to access internals/privates without slow reflection
  - The project is also currently under development
- Update release workflow
  - via GitHub Actions

Fortunately, after two weeks, I have free time.
I will take enough time for this project and make this project a top priority.

Thanks,

**Comment by unnanego** [comment]
It's gonna be a year since then soon)

**Comment by mob-sakai** [comment]
Yeah, I'm really sorry...

**Comment by YeudielG** [comment]
Any news on this?

**Comment by 37wjy** [comment]
Any news on TMPro?

**Comment by Futuremappermydud** [comment]
> 

Please! I really need this right now

**Comment by tengiplex** [comment]
TMPro is a nightmare to support lol. Don't keep your hopes up on this one.

Mob Sakai prove me wrong <3

**Comment by wangbenchong** [comment]
> I am trying to edit the shader to SRP version , choosing shader logic in BaseMaterialEffect.cs like this:
> 
> ```cs
> protected void SetNewMaterialShader(Material newMaterial, string baseName)
> {
>     //Built-in renderer pipline
>     if (GraphicsSettings.defaultRenderPipeline == null)
>     {
>         newMaterial.shader = Shader.Find(string.Format("Hidden/{0} ({1})", newMaterial.shader.name, baseName));
>     }
>     //SRP renderer pipline
>     else
>     {
>         newMaterial.shader = Shader.Find(string.Format("Hidden/SRP_{0} ({1})", newMaterial.shader.name, baseName));
>     }
> }
> ```
> 
> and now I almost done this job, just some SRP batch issue. I'll try to finish it.

seems like I finish by this fork:https://github.com/wangbenchong/UIEffect

**Comment by mob-sakai** [comment]
Hello everyone,

I am grateful for your continued use and support of UIEffect.
Since the release of the v4 preview in 2020, there has been little in the way of updates or interaction with the community, and I apologize for not being able to provide noticeable updates or responses sooner.

[🎉 UIEffect v5 is now released!](#267)
https://github.com/mob-sakai/UIEffect/releases/tag/5.0.0

**Comment by Futuremappermydud** [comment]
> Hello everyone,
> 
> I am grateful for your continued use and support of UIEffect. Since the release of the v4 preview in 2020, there has been little in the way of updates or interaction with the community, and I apologize for not being able to provide noticeable updates or responses sooner.
> 
> [🎉 UIEffect v5 is now released!](#267) [`5.0.0` (release)](https://github.com/mob-sakai/UIEffect/releases/tag/5.0.0)

Awesome!
