### ISSUE TITLE
Can't import samples in Unity2019.1 or later

### ISSUE THREAD

**Issue by elamotte** [mob-sakai/UIEffect#209]
I downloaded latest version using package manager manifest:
"com.coffee.ui-effect": "https://github.com/mob-sakai/UIEffect.git"

the version that I got is : 4.0.0-preview-3
But when I go to the package manager I don't have the "Sample Demo" section.

And I can't use it with text mesh pro, I don't have any of the textmeshpro shaders.

Do I do something wrong on import?

p.s : thanks a lot for supporting this great open source assets for all 2d games ;)

**Comment by mob-sakai** [comment]
@elamotte 
I just realized that I forgot to update PACKAGE.JSON!

**Comment by elamotte** [comment]
Thanks! It's resolved but I still can't use it with textmeshpro is that normal?

**Comment by mob-sakai** [comment]
https://github.com/mob-sakai/UIEffect/releases/tag/v4.0.0-preview.1
> TextMeshPro support has been removed from this package. It will be supported by another package.
TextMeshPro support

Sorry, TextMeshPro support for v4 is not yet available.
