### ISSUE TITLE
Blur outline

### ISSUE THREAD

**Issue by mantonijoan** [mob-sakai/UIEffect#213]
**Describe the bug**
When applying a blur to an image, a visible and blurred border is created.

**To Reproduce**
I am rendering a full screen render texture

**Expected behavior**
No border created.

**Screenshots**
Cropped images showing the borders in the top and left margins:
![Screenshot 2020-05-11 at 13 56 57](https://user-images.githubusercontent.com/9271469/81559569-f3510100-938f-11ea-9741-cd4d278a7559.png)

Expected result:
![Screenshot 2020-05-11 at 13 58 12](https://user-images.githubusercontent.com/9271469/81559568-f2b86a80-938f-11ea-9ceb-d7b7ba9b4c50.png)

**Environment (please complete the following information):**
 - Version 3.2.0
 - Unity version: 2019.2.15f1

**Additional context**
A solution to this problem may be that inside the loop of the `Tex2DBlurring` method, check if the uv coordinates are between 0 and 1.

Moreover, I found confusing the parameter `Blur Factor`. When a blur factor of 1 is applied, the blur kernel operation skips one texel, leading to strange artifacts in the resulting image.
I am currently using blur of 0.5 to achieve the maximum blurring.

**Comment by mob-sakai** [comment]
Sorry for my late reply.

UIEffect v5 is now released.
Please try it. :+1:
[🔄 Upgrading from v4 to v5](https://github.com/mob-sakai/UIEffect?tab=readme-ov-file#-upgrading-from-v4-to-v5)
