### ISSUE TITLE
[Help] No "EffectPlayer" in Script.

### ISSUE THREAD

**Issue by chaosren** [mob-sakai/UIEffect#215]
hi~ How can I set my UIShiny to loop in my script?
there is no other params can let me find **EffectPlayer** and Set it.
My UIshiny just play once and stop。
I just want to loop it .

I know its working in Editor AddComponent。
But  my project need to controll effect in script.
so I cant find way to Set  **EffectPlayer** 。

help me plz and thx ur hardwork.

![image](https://user-images.githubusercontent.com/4166553/83619530-93303200-a5be-11ea-8f4d-ecd50d48f208.png)

![image](https://user-images.githubusercontent.com/4166553/83620285-b27b8f00-a5bf-11ea-8137-76b757e8d793.png)

![image](https://user-images.githubusercontent.com/4166553/83620322-bc9d8d80-a5bf-11ea-8385-2b77e02fd228.png)

**Comment by chaosren** [comment]
@mob-sakai thx for ur hardwork 。~ LOL~

**Comment by chaosren** [comment]
@mob-sakai hi ！
after update to #4.0.0-preview.8 ，
Istill cant find EffectPlayer in my scripts. why?
namespace is change yet.
but there is no effectPlayer I can get or set.
is it still **private** in   **UIEffect.dll** ??
or there is any other way that can let me use effectplayer control my uieffect in script?


sorry for bother you twice about this question~ 

![image](https://user-images.githubusercontent.com/4166553/84098965-217f3a80-aa3b-11ea-920a-086d9c90fc31.png)

image shows UIEffect path in my project~

**Comment by mob-sakai** [comment]
@chaosren 
Thanks, I noticed my mistake!

**Comment by chaosren** [comment]
@mob-sakai  thx again .I will try it later~
