### ISSUE TITLE
UICaptureEffect gone!

### ISSUE THREAD

**Issue by buihuuloc** [mob-sakai/UIEffect#217]
Hi @mob-sakai 
How can I make the blur effect work again?

**Comment by mob-sakai** [comment]
Sorry for the late reply.
It is under preparation. Please wait a little longer.

**Comment by buihuuloc** [comment]
Thank you
Do you think It can support URP?

**Comment by mob-sakai** [comment]
Yes, of course! 👍

**Comment by mob-sakai** [comment]
This is an alternative package to `UICaptureEffect` component. (in preview)
https://github.com/mob-sakai/UIEffectSnapshot

Please note that the API may change until stable release.
