### ISSUE TITLE
Would UIEffect works with URP

### ISSUE THREAD

**Issue by ColorTwist** [mob-sakai/UIEffect#218]
Does UIEffect support URP shaders?
I couldn't find any mention regarding that in this GIT UIEffect Issues.

**Comment by buihuuloc** [comment]
It works with URP in version 4

**Comment by mob-sakai** [comment]
Sorry for my late reply.

UIEffect v5 is now released.
Please try it. :+1:
[🔄 Upgrading from v4 to v5](https://github.com/mob-sakai/UIEffect?tab=readme-ov-file#-upgrading-from-v4-to-v5)
