### ISSUE TITLE
UI Soft Shadow crash editor Image + UIEffect + UIShadow

### ISSUE THREAD

**Issue by Tokars** [mob-sakai/UIEffect#219]
**Reproduce**
Try to setup same combinations of components: [screenshot](http://dl3.joxi.net/drive/2020/07/01/0008/1075/574515/15/ee02ec61e5.jpg)

Environment:
 - Version [e.g. 4.0.0]
 - Platform Editor: Windows 10 /  Standalone WebGL
 - Unity version: [e.g. 2019.0.f1]
 - Build options: [IL2CPP]

**Comment by mob-sakai** [comment]
Sorry for my late reply.

UIEffect v5 is now released.
Please try it. :+1:
[🔄 Upgrading from v4 to v5](https://github.com/mob-sakai/UIEffect?tab=readme-ov-file#-upgrading-from-v4-to-v5)
