### ISSUE TITLE
Change UIShiny effect color

### ISSUE THREAD

**Issue by Happy-hub** [mob-sakai/UIEffect#223]
Hey there, first of all, I wanted to thank you for this beautiful project, 
been looking for something like this for a few months now, finally found it!.

I wanted to know if there's a way to change the shine effect color
 (through inspector, script, doesn't really matter).
That's it basically, thank you for your time.

**Environment (please complete the following information):**
 - Version - 3.2.0
 - Platform: Editor(Windows), Android, iOS
 - Unity version:  2019.4.3f1
 - Build options:  IL2CPP, MONO, .Net 4

**Comment by mob-sakai** [comment]
@Happy-hub 
Thanks for the feature request!
