### ISSUE TITLE
Unity 2020 support

### ISSUE THREAD

**Issue by buihuuloc** [mob-sakai/UIEffect#224]
Hi @mob-sakai 

Could you see If the package supports Unity 2020? 

Currently, we have some problem with Unity 2020

**Comment by mob-sakai** [comment]
@buihuuloc 
OK, I will check it later.

**Comment by elopezga** [comment]
If this helps, I was able to get version 3.2.0 to work on Unity 2020.1.2f1. I previously attempted to get the latest version, 4.0.0 preview 9 at the time of this writing, via package manager. I kept getting` Can't add script behaviour ScriptName. The script class can't be abstract!` error message when adding any of the UI Effects. I installed v3.2.0 via Unity package and it worked for me. So my guess is something changed between v3.2.0 and v4.0.0p9 that causes that error message to show or the installation doesn't work through Unity package manager. Would be interesting to see if v4.0.0p9 works via Unity package installation, but I don't see how the method of installation would be an issue.

**Comment by mob-sakai** [comment]
@elopezga 
Thank you for your information.

**Comment by buihuuloc** [comment]
Thanks @mob-sakai

**Comment by drallcom3** [comment]
I get various errors with 2020.2 and 4.0.0 preview 9 (from package manager).
The old downloadable 3.X version works fine and is as amazing as ever.

**Comment by mob-sakai** [comment]
@buihuuloc @elopezga @drallcom3 
I have installed UI Effect in empty project and played Demo scene, but no errors...

* Platforms
  * Editor (Mac)
  * Standalone (Mac)
* Installation
  * Add url to manifest.json: `"com.coffee.ui-effect": "https://github.com/mob-sakai/UIEffect.git",`
  * Open UPM: `openupm add com.coffee.ui-effect`
* Unity versions
  * 2020.2.0b2
  * 2020.1.6f1

I would like to know more about this issue.

**Comment by drallcom3** [comment]
I tried again and now it seems to work. I only had to place some namespaces (I think you switched it at some point).
In a fresh project it also works. 2020.2.0b5.

Btw, in 2020.2 you can directly add Git URLs in the package manager. No need to edit the manifest.

**Comment by mob-sakai** [comment]
Yes, the namespase has been changed in 4.0.0-preview.8.
I concerned that some of the class names were conflicted with other packages.
https://github.com/mob-sakai/UIEffect/commit/7f4190c8c6f294e90869767a96194ec5ac4ba57f

From what I've heard from you, it should be reverted.
Instead, use the internal modifier.

Thank you.

**Comment by drallcom3** [comment]
Yes, I missed that. All fine now. No bugs from upgrading to v4.

**Comment by mob-sakai** [comment]
@drallcom3 :+1:

**Comment by xiangsoft** [comment]
Hello I still have same problem with version 4.0.0-p9,
Can't add script behaviour ScriptName. The script class can't be abstract!
Platform:Windows
Version:2020.3.21f1c1
