### ISSUE TITLE
How to do the StaticBluredScreen

### ISSUE THREAD

**Issue by plyoung** [mob-sakai/UIEffect#225]
I was looking at mob-sakai/StaticBluredScreen and read it was moved to this project but can not find a way to implement it. 
Is it present , and if so, can someone explain how it is done with UIEffect?

**Comment by mob-sakai** [comment]
@plyoung 
StaticBluredScreen (UICapturedEffectImage) will be separated from UIEffect.
However, It is under preparation.
Please wait a little longer.

**Comment by mob-sakai** [comment]
If you need it right away, use v3.2.0.
