### ISSUE TITLE
Image repeat bug

### ISSUE THREAD

**Issue by GreenPenStudio** [mob-sakai/UIEffect#226]
If you adding **UIEffect** script for **UI Image** and set **Image Type** to **Tiled** (Sprite must have **Repeat** Wrap Mode), then set **Pixels Per Unit Multiplier** to some large number, in some time UV scale just don't changing (freezing). I think is because uv0 coordinates changes by script.

![1](https://user-images.githubusercontent.com/72493609/95310957-34a1fa00-08b7-11eb-8097-4f29da0383a9.gif)

**Comment by mob-sakai** [comment]
@GreenPenStudio 
Thank you for reporting!
(The URL I sent was wrong, the issue has been transferred.)

**Comment by mob-sakai** [comment]
Sorry for my late reply.

UIEffect v5 is now released.
Please try it. :+1:
[🔄 Upgrading from v4 to v5](https://github.com/mob-sakai/UIEffect?tab=readme-ov-file#-upgrading-from-v4-to-v5)
