### ISSUE TITLE
Not able to play effects on my button

### ISSUE THREAD

**Issue by toseefhaiderkhansugguu** [mob-sakai/UIEffect#227]
I followed all the steps in Readme file but its not working please let me know m i doing something wrong ? i have attached my project settings and button screenshoots i am using unity 2018.4.10f1
![Screenshot 2020-10-16 at 7 20 28 PM](https://user-images.githubusercontent.com/71482929/96270188-c0690400-0fe4-11eb-88af-f4dc83ade1cf.png)
![Screenshot 2020-10-16 at 7 19 24 PM](https://user-images.githubusercontent.com/71482929/96270200-c4952180-0fe4-11eb-9bc3-9f9fccbb50e3.png)

**Comment by mob-sakai** [comment]
I would like to know more about this issue.

- What is the version of UIEffect? (e.g. 4.0.0-preview.9)
- How did you install UIEffect? (e.g. via PackageManager, via OpenUPM, ...)

**Comment by toseefhaiderkhansugguu** [comment]
v0.4.0 downloaded from Git

**Comment by toseefhaiderkhansugguu** [comment]
Downloaded Unity package

**Comment by toseefhaiderkhansugguu** [comment]
adding ShinyEffectForUGUI script to my button does nothing do i need to create some material or new shader?

**Comment by mob-sakai** [comment]
Ah, I understand.

[ShinyEffectForUGUI](https://github.com/mob-sakai/ShinyEffectForUGUI) is integrated in to [UIEffect](https://github.com/mob-sakai/UIEffect).

(From readme in ShinyEffectForUGUI)
> ### NOTE: This project has been integrated into [UIEffect](https://github.com/mob-sakai/UIEffect), so we are NOT continuing development in this repository.

Please try UIEffect!

**Comment by toseefhaiderkhansugguu** [comment]
Worked Thanks 👍
