### ISSUE TITLE
The problem that the shining cycle of UI Shiny depends on the frame rate

### ISSUE THREAD

**Issue by SakamotoRyuu** [mob-sakai/UIEffect#228]
UIShinyでuGUIのImageを光らせたところ、60FPS環境と144FPS環境とで光る周期が異なる問題を発見しました。
When I lit the image of uGUI with UIShiny, I found a problem that the shining cycle is different between 60FPS environment and 144FPS.

**Comment by mob-sakai** [comment]
@SakamotoRyuu 
Thank you for the reporting!

**Comment by SakamotoRyuu** [comment]
ごめんなさい、私の勘違いだったかもしれません……
I'm sorry, it may have been my misunderstanding ...
