### ISSUE TITLE
Unclear Popup info message

### ISSUE THREAD

**Issue by Tymski** [mob-sakai/UIEffect#229]
When adding an effect to an object without an Image you get this popup that may be very unclear to a designer.
![image](https://user-images.githubusercontent.com/8183632/96587035-18a04e80-12e2-11eb-9803-65fcfc399bdd.png)

Woudn't something like this be more appropiate?  
  
```
Missing Component
This component can only be added if "Image" component is present.
```

**Comment by mob-sakai** [comment]
Sorry for my late reply.

UIEffect v5 is now released.
Please try it. :+1:
[🔄 Upgrading from v4 to v5](https://github.com/mob-sakai/UIEffect?tab=readme-ov-file#-upgrading-from-v4-to-v5)
