### ISSUE TITLE
UIShiny cycle is faster when PlanarReflection.cs attached to Water4Advanced of Standard Assets is enabled.

### ISSUE THREAD

**Issue by SakamotoRyuu** [mob-sakai/UIEffect#232]
1. Attach UIShiny to uGUI Image.
2. Install Standard Assets.
3. Place Water4Advanced included in Standard Assets in the hierarchy.
4. When you enable / disable PlanarReflection attached to Water4Advanced, UIShiny changes the frequency in which the image shines.
Unity version is 2019.1.14f1

**Comment by SakamotoRyuu** [comment]
This is the smallest project to reproduce the bug.
[Bug Report for UIShiny.zip](https://github.com/mob-sakai/UIEffect/files/5506086/Bug.Report.for.UIShiny.zip)

**Comment by rcstamp** [comment]
UIShiny speed seems to scale with rendering (more rendering = fast shine) on "Normal" mode..

**Comment by mob-sakai** [comment]
Sorry for my late reply.

UIEffect v5 is now released.
Please try it. :+1:
[🔄 Upgrading from v4 to v5](https://github.com/mob-sakai/UIEffect?tab=readme-ov-file#-upgrading-from-v4-to-v5)
