### ISSUE TITLE
How to Animate a UIEffect Effect Factor?

### ISSUE THREAD

**Issue by radiantone** [mob-sakai/UIEffect#233]
Hi,
  How would I animate an effectFactor on a UI effect? I tried the script example on the main page, but it returns null for UIEffect.

**Comment by mob-sakai** [comment]
Sorry for my late reply.

UIEffect v5 is now released.
Please try it. :+1:
[🔄 Upgrading from v4 to v5](https://github.com/mob-sakai/UIEffect?tab=readme-ov-file#-upgrading-from-v4-to-v5)
