### ISSUE TITLE
UIEffect Add only works on Gamma Color Space

### ISSUE THREAD

**Issue by GuillemDomenech** [mob-sakai/UIEffect#237]
I'm trying to achieve this effect using the Add option, white color and 0.145 Color Factor:

![](https://image.prntscr.com/image/TZRyTuV4Sw_1I3lzPzAmCQ.png)

But it only works on Gamma Color Space, here's how it looks in Linear:

![](https://image.prntscr.com/image/6XSIDVfeS7qd64KFvw580A.png)

For reference, here's the image without any effect applied:

![](https://image.prntscr.com/image/S8gBH-n6TMqeOXsfT981WQ.png)

How could I achieve the effect in the first image but with a Linear color space?

**Comment by GuillemDomenech** [comment]
@mob-sakai Do you know how I could solve this issue? I've tried adding this "color.a = pow(color.a, 2.2);" before returning the color in your "UIEffect.shader" but if I do the base color without the effect doesn't look good, it doesn't look as if I was in the gamma color space.

**Comment by mob-sakai** [comment]
Sorry for my late reply.

UIEffect v5 is now released.
Please try it. :+1:
[🔄 Upgrading from v4 to v5](https://github.com/mob-sakai/UIEffect?tab=readme-ov-file#-upgrading-from-v4-to-v5)
