### ISSUE TITLE
Not Work on mobile?

### ISSUE THREAD

**Issue by Waterbludmouse** [mob-sakai/UIEffect#238]
Hi,
I just built on my android mobile and all the UI with script will become purple or not showing...but in editor works fine.
What did I miss when build project for android/ios?
Thx!

**Comment by ltccss** [comment]
Maybe you meet the same problem
[https://github.com/mob-sakai/UIEffect/issues/235](url)

**Comment by foldthirteen** [comment]
+1 to this question.   Does anyone know if it works in iphone or if there is anything that you do to get it going?

**Comment by HiepEldest** [comment]
You have to add shaders to "Always included shaders" in the Graphics setting. Only working with import via custom package. Hope it helps

**Comment by mob-sakai** [comment]
Sorry for my late reply.

UIEffect v5 is now released.
Please try it. :+1:
[🔄 Upgrading from v4 to v5](https://github.com/mob-sakai/UIEffect?tab=readme-ov-file#-upgrading-from-v4-to-v5)
