### ISSUE TITLE
Use multiple ui elements with same shiney effect

### ISSUE THREAD

**Issue by omid3098** [mob-sakai/UIEffect#239]
Is there any way to make a single shiny effect to work on multiple ui items?
I have an ui stack with multiple elements inside:
![image](https://user-images.githubusercontent.com/6388730/115993641-84f95480-a588-11eb-9d67-9fb1dc74260c.png)

And I need to make the whole package to have shiny effect instead of adding separate effects on each one of them.

**Comment by foldthirteen** [comment]
You could create a single transparent sprite the same shape as your grouped object and use that...?

**Comment by omid3098** [comment]
No, It's not the best solution for this case. Sometimes my UI elements will have different sizes based on screen size, and it's not possible to use a single pre-baked sprite for that. and the other problem would be having animated numbers under baked sprite.

**Comment by foldthirteen** [comment]
If your UI elements are dynamically adjusting to the screen size - you can
make a single sprite that adjusts using the same ruleset.  Keep your
original sprites, just have a new rect that expands to fit the same view...

>

**Comment by wyjxp** [comment]
> 您可以创建一个与分组对象形状相同的透明 sprite，并使用它...？

UiShiny does not work on transparent objects

**Comment by wyjxp** [comment]
> You could create a single transparent sprite the same shape as your grouped object and use that...?

UiShiny does not work on transparent objects
