### ISSUE TITLE
Color mode for Shadow/ Outline

### ISSUE THREAD

**Issue by AlirezaTabasi7** [mob-sakai/UIEffect#240]
Hi there.
We really need a white shadow/ outline in our project and I thought I could ask for a color mode drop down similar to what you already implemented in UIEffect component.
Thanks in advance.

**Comment by mob-sakai** [comment]
Sorry for my late reply.

UIEffect v5 is now released.
Please try it. :+1:
[🔄 Upgrading from v4 to v5](https://github.com/mob-sakai/UIEffect?tab=readme-ov-file#-upgrading-from-v4-to-v5)
