### ISSUE TITLE
Is Text Mesh Pro supported in Version 4.0.0-preview.9 release? 

### ISSUE THREAD

**Issue by MrStump6** [mob-sakai/UIEffect#241]
My apologies if this is already obvious, but I can't seem to find a clear answer here.  I've browsed around a bit, and searched through various issues. It seems it may have been moved to a different package? but I can't find any other info on that (lots of mixed results with old info).

I'm on the *currently* latest release: Version 4.0.0-preview.9 in Unity 2021.1.24 using universal render pipeline.

I'm trying to add any sort of UIEffect to my TextMeshPro object, and getting a busted shader:
![image](https://user-images.githubusercontent.com/95729838/145138642-a084e5bf-da57-4879-9d7e-cd0f5cdf083f.png)

So, I'm thinking it's not currently supported? Please let me know!

**Comment by MrTigerZhang** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by Futuremappermydud** [comment]
it's been over a year and a half. Any updates?

**Comment by Niek352** [comment]
Any updates?

**Comment by cihadturhan** [comment]
Still not working. I just tried.
Anyone knows if it's easy to fix?

**Comment by wyjxp** [comment]
![image](https://github.com/user-attachments/assets/c4d8ff16-91df-4c59-b2bf-eff44d67d683)
I can't find the new package that supports TMP, help!

**Comment by mob-sakai** [comment]
Sorry for my late reply.

UIEffect v5 is now released.
Please try it. :+1:
[🔄 Upgrading from v4 to v5](https://github.com/mob-sakai/UIEffect?tab=readme-ov-file#-upgrading-from-v4-to-v5)
