### ISSUE TITLE
error CS0246: The type or namespace name 'UIEffect' could not be found (are you missing a using directive or an assembly reference?)

### ISSUE THREAD

**Issue by futer24** [mob-sakai/UIEffect#242]
error CS0246: The type or namespace name 'UIEffect' could not be found (are you missing a using directive or an assembly reference?)

**Comment by TheodoreMirenda** [comment]
same, cant seem to reference through script

**Comment by mob-sakai** [comment]
Sorry for my late reply.

UIEffect v5 is now released.
Please try it. :+1:
[🔄 Upgrading from v4 to v5](https://github.com/mob-sakai/UIEffect?tab=readme-ov-file#-upgrading-from-v4-to-v5)
