### ISSUE TITLE
UI shiny pingpong loop

### ISSUE THREAD

**Issue by xerm23** [mob-sakai/UIEffect#247]
Can we please get loop option that makes shine go backwards to start position instead of restarting?

**Comment by mob-sakai** [comment]
Sorry for my late reply.

UIEffect v5 is now released.
Please try it. :+1:
[🔄 Upgrading from v4 to v5](https://github.com/mob-sakai/UIEffect?tab=readme-ov-file#-upgrading-from-v4-to-v5)
