### ISSUE TITLE
PS4 - effects not working correctly (purple color)

### ISSUE THREAD

**Issue by Nappingdragon** [mob-sakai/UIEffect#250]
Error log attached
[Editor2.log](https://github.com/mob-sakai/UIEffect/files/8534411/Editor2.log)
UIEffect 4.0.0 - preview 9
UI Effect snapshot 1.0.0
UI Soft Mask 1.0.0

imported using git in manifest
Unity 2019.4.37
IL2CPP, .Net 4.x, Built-In

all three packages give errors when building for PS4 (other platforms ok)
build can be done but in game, features using this plugins either not visible (soft mask) or visible as purple color (background blur, transition effects) 
win, Xbox, switch work fine

PS there is one similar but no exact issue here and i've actually used that information to fix some other bugs in different shader, but it'd be great to have fix for this problem from the developer

**Comment by mob-sakai** [comment]
Sorry for my late reply.

UIEffect v5 is now released.
Please try it. :+1:
[🔄 Upgrading from v4 to v5](https://github.com/mob-sakai/UIEffect?tab=readme-ov-file#-upgrading-from-v4-to-v5)
