### ISSUE TITLE
Soft Shadow Glow Effect

### ISSUE THREAD

**Issue by darkdoom973** [mob-sakai/UIEffect#253]
Reading Manner = Image, then associated Text

![image](https://user-images.githubusercontent.com/100094370/178113875-1ae82996-e7fb-44b4-ace8-1faa6f9e2c5d.png)
This is the effect I want to achieve, how can I do so???
![image](https://user-images.githubusercontent.com/100094370/178113960-6f665b97-57f9-42ca-b83d-92b7f06857dd.png)
I understand this is having two of UI Shadow scripts.
![image](https://user-images.githubusercontent.com/100094370/178113986-fa5c3ca7-82c3-43c8-b9e1-fc1dd3f817ec.png)
I don't understand what are these??
![image](https://user-images.githubusercontent.com/100094370/178114047-19ac4057-d55f-40c2-b254-b02ade81e20e.png)
I am able to get the normal effect
![image](https://user-images.githubusercontent.com/100094370/178114063-711c584d-c9cd-4cd8-a152-8e4d3735638d.png)
I want this soft outline shadow

**Comment by BonnyShen** [comment]
you should add `UIEffect` component before your `UIShadow`. And change the blur mode . 
After that , you'll see the `Blur Factor` param at the end of UIShadow.

![image](https://user-images.githubusercontent.com/1468447/180902073-47f55503-7f10-454e-8944-4822ceee0e1e.png)

**Comment by Rafael-Dolfe** [comment]
This did not work on Unity 2022.2.17, URP.

**Comment by the91end** [comment]
> you should add `UIEffect` component before your `UIShadow`. And change the blur mode . After that , you'll see the `Blur Factor` param at the end of UIShadow.
> 
> ![image](https://user-images.githubusercontent.com/1468447/180902073-47f55503-7f10-454e-8944-4822ceee0e1e.png)

Thank you!
This should be in documentation IMO

**Comment by mob-sakai** [comment]
Sorry for my late reply.

UIEffect v5 is now released.
Please try it. :+1:
[🔄 Upgrading from v4 to v5](https://github.com/mob-sakai/UIEffect?tab=readme-ov-file#-upgrading-from-v4-to-v5)
