### ISSUE TITLE
Can I affect UIEffect for All children of an UI Object ?

### ISSUE THREAD

**Issue by PhucDev02** [mob-sakai/UIEffect#257]
Can I affect UIEffect for All children of an UI Object ?

**Comment by GuillemDomenech** [comment]
Yes please

**Comment by mob-sakai** [comment]
Sorry for my late reply.

UIEffect v5 is now released.
Please try it. :+1:
[🔄 Upgrading from v4 to v5](https://github.com/mob-sakai/UIEffect?tab=readme-ov-file#-upgrading-from-v4-to-v5)
