### ISSUE TITLE
Working with RectMask2D in newer Unity versions?

### ISSUE THREAD

**Issue by swoy45** [mob-sakai/UIEffect#262]
**Is your feature request related to a problem? Please describe.**
RectMask2D is now working via _ClipRect parameter in shader and using TEXCOORD2 for mask instead of stencil. But UIEffect shaders using TEXCOORD2 for its purposes and simple adding those masking code and binding mask to TEXCOORD3 is not working.

**Describe the solution you'd like**
Update UIEffect, UIDissolve and UIShiny shaders and corresponding includes in UIEffectSprite.cginc to modern version of Unity built-in UI shader.

**Describe alternatives you've considered**
Support of SoftMaskForGUI?

**Comment by mob-sakai** [comment]
Sorry for my late reply.

UIEffect v5 is now released.
Please try it. :+1:
[🔄 Upgrading from v4 to v5](https://github.com/mob-sakai/UIEffect?tab=readme-ov-file#-upgrading-from-v4-to-v5)
