### ISSUE TITLE
Create target list and apply all at once.

### ISSUE THREAD

**Issue by Corfing** [mob-sakai/UIEffect#263]
NOTE: Your issue may already be reported! Please search on the [issue tracker](../) before creating one.

**Describe what help do you need**
First of all I would like to say that your script is very well written.
However, since I use a lot of UI Effect scripts, it is difficult to manage them.
So, I want to create a list of objects that use the same effect in one scene and apply them at once.

**Environment (please complete the following information):**
 - Version [e.g. 4.0.0]
 - unity 2022.3.24

**Comment by mob-sakai** [comment]
Sorry for my late reply.

UIEffect v5 is now released.
Please try it. :+1:
[🔄 Upgrading from v4 to v5](https://github.com/mob-sakai/UIEffect?tab=readme-ov-file#-upgrading-from-v4-to-v5)
