### ISSUE TITLE
[v4] UIShiny and TextMeshProUGUI with outline not working in unity 6

### ISSUE THREAD

**Issue by JayRojivadiya** [mob-sakai/UIEffect#266]
Please see the attached file
![Capture](https://github.com/user-attachments/assets/6074ea47-746b-49a1-b20c-b2e8f43b9c97)
The outline should be black,
Instead vertical gradient in the outline appears from the outline color (black) to the text color (yellow). 

Possible reasons could be:
TextMesh Pro got an API upgrade and  integrated into Unity UI 2.0.0
Please help!

**Comment by mob-sakai** [comment]
Sorry for my late reply.

UIEffect v5 is now released.
Please try it. :+1:
[🔄 Upgrading from v4 to v5](https://github.com/mob-sakai/UIEffect?tab=readme-ov-file#-upgrading-from-v4-to-v5)

**Comment by JayRojivadiya** [comment]
The issue is fixed in v5. Thank you.
