### ISSUE TITLE
[Help] How to Install v5

### ISSUE THREAD

**Issue by PalaNolho** [mob-sakai/UIEffect#268]
I'm not very experienced in installing things in Unity from GitHub and fml I'm not being able to install it using the UPPM and selecting "from Git"

I enter the URL and press ENTER (or click the install button) but nothing happens :S . Am I doing something wrong ?
(noticed that the console shows the following error:
```
[Package Manager Window] Error adding package: https://github.com/mob-sakai/UIEffect.git?path=Packages/src.
Unable to add package [https://github.com/mob-sakai/UIEffect.git?path=Packages/src]:
  No 'git' executable was found. Please install Git on your system then restart Unity and Unity Hub
UnityEditor.EditorApplication:Internal_CallUpdateFunctions ()
```

would it be possible to offer a repacked unity asset like in previous versions?

Happy for any help anyone can provide.

Best regards

**Comment by mob-sakai** [comment]
Thank you for your reporting!

As the error message indicates, you need to have Git installed on your PC to install via Git URL.  
Install Git, or as an alternative, there are two solutions:

## Solution 1: Install via OpenUPM (Manual)

OpenUPM is an unofficial package registry.  
[Follow the instructions (See 'Manual Installation' in the right pane)](https://openupm.com/packages/com.coffee.ui-effect) to add OpenUPM as a scoped registry, then install `com.coffee.ui-effect`.  

## Solution 2: Install as an Embedded Package

Follow the instructions to extract the package directory (`Packages/src`) from the source code (zip) and copy it into the `<your_project>/Packages` directory.  
https://github.com/mob-sakai/UIEffect?tab=readme-ov-file#install-as-embedded-package

Good luck! 👍
