### ISSUE TITLE
[Question] Not all effects work in Space Camerar - Overlay?

### ISSUE THREAD

**Issue by PalaNolho** [mob-sakai/UIEffect#272]
Hi, I have been playing around with the UI Effects and I'm getting different experiences between the editor view and the play view.

In particular related to glows and other effects.

It seems that some effects only work in screen space = Worls or Camera and others will only work partially in screen space = Overlay and some will not even work in screen space = Overlay.

Is my understanding correct? are these effects documented or is there an easy way to know which ones will fully work in screen space Overlay ?

Thank in advance.

**Comment by mob-sakai** [comment]
Thank you for your reporting!
Hmm, it's strange. UIEffect should support all render modes.

Tell me about your develop/build environment.
 - UIEffect version [e.g. 5.0.0]
 - Platform: [e.g. Editor(Windows/Mac), Standalone(Windows/Mac), iOS, Android, WebGL]
 - Unity version: [e.g. 2022.2.0f1]
 - Build options: [e.g. IL2CPP, .Net 4.x, URP/HDRP]

Could you please attach a minimal project (included `Assets`, `Packages` and `ProjectSettings` directories) that reproduces the issue?
Of course, you don't need to include any secret assets from your project. Feel free to use free assets instead.

![repos](https://user-images.githubusercontent.com/12690315/130532459-0b5076f1-9b07-460b-b448-1d487e40ec1f.png)

**Comment by mob-sakai** [comment]
For example, this is a demo scene. (Editor (Mac), Unity 2021.3.30f1, URP 15.0.7)
![](https://github.com/user-attachments/assets/457b9b3d-3363-4309-ac7e-dc4b75a5d15d)

**Comment by PalaNolho** [comment]
Here is a test scene.
[Test-Scene.zip](https://github.com/user-attachments/files/17874418/Test-Scene.zip)

You need to install the UIEffects asset (not included in the package
I'm currently using this on:
![image](https://github.com/user-attachments/assets/412f7f5e-2631-4526-9687-923bb9f97438)

**Other details:**
- Unity 6 LTS
- Windows 11 64bits
- UIEffects v5.0.0
- URP
- (if you need more information please let me know what)

The scene has 2 canvas: one Overlay and one Camera
I duplicated the components and placed them on both cavas to see the difference.
You can see that in the Overlay one, not all works and between editor window and camera window, the Overlay shows differences

![image](https://github.com/user-attachments/assets/ce64ab31-870b-4599-b80c-d51e20835144)

I have also included a post-processing (volume) component otherwise anything related with glow will not work even in the camera mode canvas.

hope it helps.

**Comment by mob-sakai** [comment]
Hmm, as far as I know, `Screen Space - Overlay` canvas does not support HDR colors or PostProcessing.  
Additionally, the scene view camera settings are based on the camera with `MainCamera` tag.

As a test, try turning off `Output > HDR Rendering` in the Camera inspector.  
The same results will be displayed in both the Game View and the Scene View.

---

If you want PostProcessing (and HDR colors), please use `Screen Space - Camera`.

**Comment by PalaNolho** [comment]
kk thanks
