### ISSUE TITLE
[Help] set Color Filter color

### ISSUE THREAD

**Issue by PalaNolho** [mob-sakai/UIEffect#273]
Hi,

I have an UIEffect with a Color Filter and I would like to change its color through a script.

how should I do that considering it's an HDR color? could you share an example?

Many thanks

**Comment by mob-sakai** [comment]
For example, the following extension methods can be created and used:

```cs
public static class ColorExtensions
{
    public static Color ToHdr(this Color c, float intensity)
    {
        var factor = Mathf.Pow(2, intensity);
        return new Color(c.r * factor, c.g * factor, c.b * factor, c.a);
    }
}

...

uiEffect.color = Color.red.ToHdr(intensity: 1.5);
```

**Comment by PalaNolho** [comment]
that helps me understand the HRR color, thanks.

But how to I change/set the color used in the ColorFilter??

![image](https://github.com/user-attachments/assets/9c553e87-5d55-4059-a6ce-ea7580a1093a)

**Comment by mob-sakai** [comment]
Use the `UIEffect.color` property.

```cs
var uiEffect = GetComponent<UIEffect>();
uiEffect.color = new Color(1,0,0).ToHdr(intensity: 1.5);
```

**Comment by PalaNolho** [comment]
worked 👍
