### ISSUE TITLE
[v5] Previewing UIEffectTweener while not in Play mode

### ISSUE THREAD

**Issue by kallecollan** [mob-sakai/UIEffect#278]
Is there a way to preview the effects of UIEffectTweener while not in Play mode? So far I haven't seen any references in the README regarding this feature.

I see that there is a small Play icon within the UIEffectTweener but pressing it outside Play mode doesn't do anything.
![image](https://github.com/user-attachments/assets/4926aec4-d24c-4f2a-97b1-7911c516869d)

**Comment by mob-sakai** [comment]
It is scheduled to be released in version 5.1.0! :+1:
