### ISSUE TITLE
[V5]How to use Direction in UIEffectTweener correctly?

### ISSUE THREAD

**Issue by xfvvvv** [mob-sakai/UIEffect#281]
Hello,

When I set Direction to Reverse, when the user restarts or sets time (UIEffectTweener.Duration), the rate value returned is always 0.Unable to play in reverse order as desired.

Thank you

**Comment by mob-sakai** [comment]
Thank you for your reporting!

**Comment by mob-sakai** [comment]
It is scheduled to be released in version 5.1.0! :+1:
