### ISSUE TITLE
[v5] UI Effect compoent is not work with TextMeshPro

### ISSUE THREAD

**Issue by CorbyO** [mob-sakai/UIEffect#284]
UI Effect compoent is not work with TextMeshPro.
My font asset used  `textmeshpro/mobile/bitmap` shader and shader changed to `Hidden/UI/Default` after edting the component.
is this asset supporting for `textmeshpro/mobile/bitmap` shader?
(I didn't test sdf font asset)

**Screenshots**
![image](https://github.com/user-attachments/assets/f2eb985c-42eb-41ff-8e75-5b6b98f4dcec)
![image](https://github.com/user-attachments/assets/caf51cd7-ebf7-4fa8-8861-34d7ad1b4cd9)
![image](https://github.com/user-attachments/assets/f8ae4ccc-ded2-43be-9256-9b4ef0649af6)

**Environment (please complete the following information):**
 - Version: 5
 - Platform: Windows 11
 - Unity version: 6000.0.29f1
 - Build options: Editor

**Comment by mob-sakai** [comment]
Thank you for your reporting!
`TextMeshPro/Mobile/Bitmap` shader is currently unsupported.
However, adding support for it is straightforward. 👍

Extract the following zip file and place the shaders in `Assets/Samples/UI Effect/5.0.0` directory.
[TMP_Bitmap-UIEffect-Unity6.zip](https://github.com/user-attachments/files/18092098/TMP_Bitmap-UIEffect-Unity6.zip)

**Comment by mob-sakai** [comment]
![](https://github.com/user-attachments/assets/05591fdb-73c5-4c88-8766-0f21c78432ba)

**Comment by CorbyO** [comment]
Thanks for sharing that shader.

I've applied that shader and the component is finding it just fine, but the color-related functionality isn't working as expected.
I saw a commit to the development branch, should I wait for version 5.1?
![image](https://github.com/user-attachments/assets/2b9ad65b-c50d-43b1-87f9-a034f9c384a5)

**Comment by mob-sakai** [comment]
Here’s the workaround you can try until version 5.1.0 is released:  

1. Find the `uieffect_frag` function in the shader files.  
2. Modify the return value as follows:  
    ```shader
    return color * color.a;
    ```

**Comment by CorbyO** [comment]
Thank you. color problem is solved!
