### ISSUE TITLE
UIEffect Frequently Causes TextMeshPro Text to Display as Black Blocks When Saving Prefabs in Editor

### ISSUE THREAD

**Issue by 6ag** [mob-sakai/UIEffect#285]
Hello,

When using the TextMeshPro text component with UIEffect in the Unity Editor, saving the UI prefab often results in the TextMeshPro texts appearing as black blocks. This issue disrupts the workflow, especially for users who frequently save their work. Below are the detailed observations and steps to reproduce the problem.

**Environment Information:**
- **Operating System:** macOS 14.6.1
- **Unity Version:** 2021.3.45
- **UIEffect Version:** 5.0.0
- **TextMeshPro Version:** 3.0.9

**Steps to Reproduce:**
1. Create a UI element in Unity that includes multiple TextMeshPro components.
2. Add the UIEffect component and adjust the effect settings as desired.
3. Save the UI prefab.
4. Observe the saved prefab; the TextMeshPro texts display as black blocks with high probability.
5. If multiple TextMeshPro texts are present, editing one of the black-block texts will only restore that specific text to normal, while others remain as black blocks.

**Expected Result:**
All TextMeshPro texts should display normally with the applied UIEffect after saving the prefab.

**Actual Result:**
- Saving the prefab causes TextMeshPro texts to display as black blocks with high probability.
- When multiple TextMeshPro texts are present, editing one restores only that specific text, leaving others as black blocks.
- This issue occurs exclusively in the Unity Editor.
- The problem is especially troublesome for users who habitually save their work frequently.

**Additional Details:**
- **Error Logs:** There are no related error logs.
- **UIEffect Settings:** Tried different UIEffect settings, but the issue persists consistently.
- **Other Plugins/Scripts:** [Please mention if any other plugins or scripts are in use]
- **Troubleshooting Steps Taken:**
  - Verified that the issue does not occur when not using UIEffect.
  - Ensured that both UIEffect and TextMeshPro are updated to their latest compatible versions.
  - Tested in a new Unity project with only UIEffect and TextMeshPro installed; the issue still occurs.

**Temporary Workaround:**
Making any modifications to a TextMeshPro component or the UIEffect component, or reopening the UI prefab, causes the affected text to display normally again. However, this needs to be done individually for each problematic TextMeshPro text, which is time-consuming and inefficient.

**Impact:**
This issue significantly hampers the development process by requiring repetitive fixes after each save, making it difficult to maintain productivity and ensure visual consistency in UI elements.

**Request:**
I would appreciate any assistance or guidance on resolving this issue. If additional information is needed, please let me know. Thank you for your support!

<img width="263" alt="image" src="https://github.com/user-attachments/assets/6800ee3b-4db9-4cf9-8c4c-fff41aa52e96" />

**Comment by mob-sakai** [comment]
Thank you for your reporting!
Could you please attach a minimal project (included `Assets`, `Packages` and `ProjectSettings` directories) that reproduces the issue?
Of course, you don't need to include any secret assets from your project. Feel free to use free assets instead.

![repos](https://user-images.githubusercontent.com/12690315/130532459-0b5076f1-9b07-460b-b448-1d487e40ec1f.png)

**Comment by 6ag** [comment]
This is a minimal project to reproduce the issue:

1. Double-click `TestUIPrefab`.
2. Modify the `Text Input` of the `Text (TMP)` component.
3. Press `Command + S` to save the prefab.

This will reproduce the issue.

[UIEffect-Test.zip](https://github.com/user-attachments/files/18135358/UIEffect-Test.zip)

![WX20241214-181225@2x](https://github.com/user-attachments/assets/210e3850-70cc-4b53-a79a-b4ba86116dd2)

**Comment by mob-sakai** [comment]
Thank you! 👍

**Comment by mob-sakai** [comment]
The issue is reproduced on my environment.

**Comment by 6ag** [comment]
Thank you for the update. I’ve updated to version **5.0.1** and everything works perfectly now.

I appreciate your quick response and support!
