### ISSUE TITLE
TextMeshProUGUI Text with UIEffect can't change transparency

### ISSUE THREAD

**Issue by ljaf001** [mob-sakai/UIEffect#287]
NOTE: Your issue may already be reported! Please search on the [issue tracker](../) before creating one.

**Describe the Feature**
When Shiny is used on TextMeshProUGUI, if the transparency of TextMeshProUGUI is set, the Shiny effect will appear particularly bright, as shown below.
![image](https://github.com/user-attachments/assets/02ff2fd8-c7a2-4caf-a798-f09d687d0626)

**Describe the solution you'd like**
It is best to change the transparency of the TextMeshProUGUI together with the Shiny effect. Or, it is OK to change the transparency without Shiny effect.

**Environment (please complete the following information):**

Version [5.0.1]
Platform: [Editor(Windows/Mac), Standalone(Windows/Mac), iOS, Android, WebGL]
Unity version: [2021.3.41f1]
Build options: [IL2CPP, .Net 4.x, LWRP]

**Additional context**

**Comment by mob-sakai** [comment]
Thank you for your reporting!
Could you please attach a minimal project (included `Assets`, `Packages` and `ProjectSettings` directories) that reproduces the issue?
Of course, you don't need to include any secret assets from your project. Feel free to use free assets instead.

![repos](https://user-images.githubusercontent.com/12690315/130532459-0b5076f1-9b07-460b-b448-1d487e40ec1f.png)

**Comment by ljaf001** [comment]
There are three TextMeshProUGUIs under the RootCanvas in TestScene. Label2 and label3 both have their transparency set to 100, but there is a UIEffect on label2, so it looks like the transparency has not changed.
[Uploading TestProject.zip…]()

**Comment by mob-sakai** [comment]
👍
