### ISSUE TITLE
How to Apply effects to all child images?

### ISSUE THREAD

**Issue by alexxtaurus83** [mob-sakai/UIEffect#288]
**Describe what help do you need**
I have following structure:
 GameObjects - Image background
    GameObjects - Image icon
    GameObjects - Image - icon2

How can I apply Effect to all images including child ones?  (Similar like canvasGroup can control Alfa for all child objects)

**Comment by mob-sakai** [comment]
Add `UIEffectReplica` component to the children and set the parent element as the target.
https://github.com/mob-sakai/UIEffect?tab=readme-ov-file#component-uieffectreplica
