### ISSUE TITLE
How to fire event after animation ends?

### ISSUE THREAD

**Issue by alexxtaurus83** [mob-sakai/UIEffect#289]
A description of the question.

I need to add event after animation ends after PlayForward() call. 
How to do this?

var tweener = wikiItemPresenter.gameObject.AddComponent<UIEffectTweener>();
tweener.wrapMode = UIEffectTweener.WrapMode.Once;
tweener.duration = effectDuration;
tweener.curve = AnimationCurve.Linear(0, 1, 1, 0);          
tweener.PlayForward();

**Comment by mob-sakai** [comment]
Indeed, that is a common use case.  
I will add an `OnComplete` event later.  

As a workaround, you can monitor `isTweening` in a coroutine.
