### ISSUE TITLE
Animation with color changing is not supported?

### ISSUE THREAD

**Issue by stanislavkaliuk** [mob-sakai/UIEffect#70]
Is this feature enabled in your plugin? I try to change alpha channel of outline/shadow color and it doesn't take effect.

**Comment by mob-sakai** [comment]
Hi, @stanislavkaliuk.

Do you use UnityEngine.UI.Outline/Shadow  component?

**Comment by mob-sakai** [comment]
Oh, sorry.
I found a bug about this!

**Comment by mob-sakai** [comment]
Oh, I was wrong.
"I found a bug" was a misunderstanding.

**Comment by stanislavkaliuk** [comment]
I tried to modify Shadow color property. And it takes no effect. But changing alpha in color mode works perfectly.

**Comment by mob-sakai** [comment]
Thank you for information :)

**Comment by mob-sakai** [comment]
Please test this prefab.
[Sample.unitypackage.zip](https://github.com/mob-sakai/UIEffect/files/2048760/Sample.unitypackage.zip)

ColorMode: None, Set, Add, Sub
ShadowMode: Shadow (10, 10)
![5 -29-2018 23-58-49](https://user-images.githubusercontent.com/12690315/40667249-9e7b9fa2-639c-11e8-9cfa-dd6fdbe72b99.gif)

**Comment by stanislavkaliuk** [comment]
Yeah, it's working. Sorry for a trouble.

**Comment by mob-sakai** [comment]
I'm happy to hear that 😄

**Comment by stanislavkaliuk** [comment]
Have a question. Do you plan to add soft shadows feature?

**Comment by mob-sakai** [comment]
You can use soft shadow by using blur.
Please set as follows.
1. Set `Blur Mode` to `Fast` or `Medium` or `Detail`
2. Set `Blur` to `0` (for blurring only shadow)
3. Set `Shadow Blur` to `1`
