### ISSUE TITLE
Change dissolve texture

### ISSUE THREAD

**Issue by teacoat** [mob-sakai/UIEffect#75]
I have a bunch of UI elements that I want to dissolve one after another, change the text, and then dissolve it back in. This doesn't look great with the dissolve texture for each one being the same. 

Is there any way to change the texture being used? Even more amazing would be something I can call on each UIDissolve to generate a new perlin noise texture on the fly?

Thanks for the great asset!

**Comment by mob-sakai** [comment]
Hi, @ teacoat.

It's good feature!
It is not supported yet, but will be supported soon, I think.

Now, I have two ideas.

### 1: Create new material instance with another noise texture.
You can use any texture.

### 2: Generate perlin noise in shader with some parameters.
Noise pattern is generated without material instances.
To send parameters to the shader, use UIVertex.normal etc.

**Comment by mob-sakai** [comment]
If you want to do it immediately, please make the following modifications.

#### 1. Comment out the `ISerializationCallbackReceiver` interface from` UIDissolve.cs`
```cs
public class UIDissolve: BaseMeshEffect
#if UNITY_EDITOR
//	, ISerializationCallbackReceiver
# endif
```

#### 2. Create a new dissolve material
* Set the `UI/Hidden/UI-Effect-Dissolve` shader
* Set inspector to debug mode and set shader keyword according to ColorMode.  
(Additive: UI_COLOR_ADD, Subtract: UI_COLOR_SUB, Override: UI_COLOR_SET)  
![5 -30-2018 12-17-06](https://user-images.githubusercontent.com/12690315/40697031-6ec98294-6403-11e8-95c4-6150058a3a64.gif)
* Set your noise texture

#### 3. Set the material as EffectMaterial and disable/enable component  
![5 -30-2018 12-25-21](https://user-images.githubusercontent.com/12690315/40697302-97e13914-6404-11e8-9073-3253b54e994b.gif)

**Comment by teacoat** [comment]
Will this make the material in UIDissolve public and accessible during runtime to change textures as well?

**Comment by mob-sakai** [comment]
I think it is possible by creating a new material instance.

https://gist.github.com/mob-sakai/57341af242e28f55aa2b579981364559
1. Import above script to your project.
2. Add a `ChangeDissolveTexture` component to the GameObject contains UIDissolve.
3. You can change the texture from the inspector or a script like this:  
`changeDissolveTexture.dissolveTexture = _your_dissolve_texture;`

**Comment by mob-sakai** [comment]
hmm.. I think that the `noiseTexture` property should be added to UIDissolve.

**Comment by teacoat** [comment]
A noise texture property and a method you can call to regenerate the noise texture would make this perfect!

**Comment by teacoat** [comment]
I will try your other solutions sometime this weekend and let you know!
